### ISSUE TITLE
Default document_type is "doc" instead of "_doc" ?

### ISSUE THREAD

**Issue by sherifabdlnaby** [logstash-plugins/logstash-output-elasticsearch#796] opened 2018-09-18 16:36 UTC
Using Elasticsearch output plugin, the documents indexed have the type "doc" instead of "_doc", isn't the standard type now after deprecating types is "_doc" ?
- Version: 6.4
- Operating System: Ubuntu 18.04

**Comment by Battleroid** [comment] 2018-10-29 18:48
The entire stack unfortunately uses `doc` instead of `_doc` which is backwards from my point of view. This just makes transitioning later on more effort.

**Comment by AnthonyJClink** [comment] 2020-03-11 19:25
This bug is also giving me the following error:

Rejecting mapping update to [unregistered-2020] as the final mapping would have more than 1 type: [_doc, doc]

we mapped this index with _doc

so I am not sure how to force logstash to send _doc

**Comment by Battleroid** [comment] 2020-03-12 16:02
@AnthonyJClink you should be able to set `document_type => "_doc"`

**Comment by kares** [comment] 2022-02-03 06:50
closing as duplicate of https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/868

**Closed by kares** 2022-02-03 06:50 UTC
