### ISSUE TITLE
create index failed

### ISSUE THREAD

**Issue by minminmsn** [logstash-plugins/logstash-output-elasticsearch#719] opened 2018-01-04 03:24 UTC
every day 00:00:00 auto create index ,but today failed

logstash-6.0.0-1.noarch
elasticsearch-6.0.0-1.noarch
CentOS Linux release 7.4.1708 (Core) 

error log
[2018-01-03T00:00:07,707][INFO ][logstash.outputs.elasticsearch] retrying failed action with response code: 403 ({"type"=>"cluster_block_exception", "reason"=>"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"})

**Comment by minminmsn** [comment] 2018-01-08 13:06
@olafz tks，maybe i can setting nginx_template  link this :   
[root@kafka249 templates]# cat nginx_template
{
  "template" : "filebeat-*",
  "settings" : {
    "index.refresh_interval" : "5s",
     "index.number_of_shards": "8",
     "index.number_of_replicas": "1",
#     "blocks.read_only": false,
#     "blocks.read_only_allow_delete": false
  },

**Comment by olafz** [comment] 2018-01-08 19:33
@minminmsn You can, but it's probably rather useless: these settings are a last resort for Elasticsearch to prevent nodes from running out of disk space.

ES enforces a read-only index block (`blocks.read_only_allow_delete`) on every index that has one or more shards allocated on a node where the diskspace in use is higher than the flood stage watermark.

So, this was probably caused by a node running out of disk space, and then setting these values in the template makes little sense, IMHO.

**Comment by minminmsn** [comment] 2018-01-09 02:24
@olafz  i see ,thank you very much!

**Comment by jsvd** [comment] 2018-05-17 10:45
closing since was just a normal response of high watermarks being high in elasticsearch

**Closed by jsvd** 2018-05-17 10:45 UTC
