### ISSUE TITLE
Failed to flush outgoing items

### ISSUE THREAD

**Issue by dcodix** [logstash-plugins/logstash-output-elasticsearch#63] opened 2015-02-27 08:38 UTC
I have been redirected here from my original issue in the wrong place on the [main elasticsearch project](https://github.com/elasticsearch/logstash/issues/2697).
I've been also been told there that maybe the issue was already addressed but I didn't find the issue here, so I just move the issue here:

I am using elasticsearch-1.4.4-1(stand alone not clusterized) and logstash-1.4.2-1_2c0f5a1 reading data from a redis server.
For a while everything works like a charm, but after a while logstash stops being able to write to ES. The internal logstash queues fill up and logstash stops reading from redis.

When it happens ES is ok, and I solve the problem by restarting logstash.

At the logs I can see lots of messages like:
```
{:timestamp=>"2015-02-24T03:50:10.034000+0000", :message=>"Failed to flush outgoing items", :outgoing_count=>67, :exception=>#<NameError: no method 'type' for arguments (org.jruby.RubyFixnum) on Java::OrgElasticsearchActionIndex::IndexRequest>, :backtrace=>["/opt/logstash/lib/logstash/outputs/elasticsearch/protocol.rb:225:in `build_request'", "/opt/logstash/lib/logstash/outputs/elasticsearch/protocol.rb:205:in `bulk'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/lib/logstash/outputs/elasticsearch/protocol.rb:204:in `bulk'", "/opt/logstash/lib/logstash/outputs/elasticsearch.rb:315:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1339:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:193:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:112:in `buffer_initialize'", "org/jruby/RubyKernel.java:1521:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:110:in `buffer_initialize'"], :level=>:warn}
```

After restarting logstash everything works like a charm again.

I read [here](http://serverfault.com/questions/565469/logstash-server-log-file-flooded-with-failed-to-flush-outgoing-items-error-mes) that it happens when the ES embeded version on logstash is not the same of the standalone ES. In my case that would be true, but I disabled the embeded ES.
If this is true, there is no way of having it working with the last ES version as (if I am not wrong) I am already using the last logstash version available.

I was thinking to use "http" protocol instead of "elasticsearch" as documentation stands that it should work with any ES version, but I read also on the "elasticsearch" protocol documentation:
```This output lets you store logs in Elasticsearch and is the most recommended output for Logstash. If you plan on using the Kibana web interface, you’ll need to use this output.```

As I am also using kibana (3 and 4), I am not sure if I can use the "http" protocol anyway.

So, first of all, I would like to know if this is a bug or if it is true that you can only use safely the "elasticsearch" protocol if the standalone ES version is the same of the embeded one.
In the case this is normal, and it is not an issue, would it work using the "http" protocol?

My logstash output:
```
output {
  #stdout { codec => rubydebug }
  elasticsearch {
    embedded => false
    host => "127.0.0.1"
    protocol => transport
  }
}
```

**Comment by jordansissel** [comment] 2015-03-02 17:40
@dcodix can you attach your full logstash config?

**Comment by jordansissel** [comment] 2015-03-02 17:41
> I read here that it happens when the ES embeded version on logstash is not the same of the standalone

I have no influence over the content on that forum.


> but I disabled the embeded ES.

This doesn't do what you think it dose. `embedded` is false by default, also.

**Comment by dcodix** [comment] 2015-03-02 20:03
@jordansissel 
Yes, here you have my full config:

```
input {
  redis {
    host => 'myhost'
    data_type => 'list'
    key => 'mykey'
    type => 'logs'
  }
}
filter {
  if [type] == "mytype1" {
    grok {
     match => [
        'message' , '%{IPORHOST:clientip}%{GREEDYDATA}(?:%{WORD:ident}|-) \[%{HTTPDATE:log_timestamp}\] \"(?:%{WORD:verb} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion})?|%{DATA:rawrequest})\" %{NUMBER:response} (?:%{NUMBER:bytes}|-) (?:%{QS:referrer}|-) %{QS:agent} %{NUMBER:request_time:float} %{NUMBER:upstream_time:float} %{WORD:country_code} data=%{GREEDYDATA:request_body}',
        'message' , '%{COMBINEDAPACHELOG}'
     ]
    }
    date {
      locale => "en"
      match => [ "log_timestamp", "dd/MMM/yyyy:HH:mm:ss Z" ]
    }
    urldecode {
      field => request_body
    }
    mutate {
     remove_field => [ "message" ]
     add_field => {
        "reverse_ip" => ["%{clientip}"]
     }
    }
    json {
      source => "request_body"
    }
    dns {
      reverse => ["reverse_ip"]
      action => [ replace ]
    }
  }

  if [type] == "nginx-access" {
    grok {
      match => [
        'message' , '%{IPORHOST:clientip}%{GREEDYDATA}(?:%{WORD:ident}|-) \[%{HTTPDATE:timestamp}\] \"(?:%{WORD:verb} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion})?|%{DATA:rawrequest})\" %{NUMBER:response} (?:%{NUMBER:bytes}|-) (?:%{QS:referrer}|-) %{QS:agent} %{NUMBER:request_time:float} %{NUMBER:upstream_time:float} %{GREEDYDATA:request_body}',
        'message' , '%{COMBINEDAPACHELOG}'
      ]
    }
  }

  if [type] == "nginx-error" {
    grok {
      match => [
        'message' , '%{DATESTAMP} \[%{LOGLEVEL:severity}\] %{POSINT:pid}#%{NUMBER}: %{GREEDYDATA:data}(?:, client: %{IPORHOST:client})(?:, server: %{IPORHOST:request_hostname})(?:, request: %{QS:request})'
      ]
    }
  }

  if [type] == "linux_syslog" {
    grok {
      match => [
        'message' ,  '(?:%{SYSLOGTIMESTAMP:timestamp})%{GREEDYDATA:sysessage}'
      ]
    }
    date {
      match => [ "timestamp", "MMM dd HH:mm:ss", "MMM  d HH:mm:ss", "ISO8601", "UNIX" ]
      locale => en
    }
  }

  if [type] == "mysql-slowlog" {
    grok {
      match => [
        'message' , '^# Time:',
        'message' , '^Time',
        'message' , 'MySQL Community Server',
        'message' , '^Tcp port:'
      ]
      add_tag => ["discard-mysql-slowlog"]
    }
    grok {
      match => [
        'message' , '(?m)^# User@Host: %{USER:user}\[[^\]]+\] @ %{WORD} \[%{IP:ip_addr}?]%{SPACE}Id:%{SPACE}%{NUMBER:idd}\n# Query_time: %{NUMBER:duration:float} \s*Lock_time: %{NUMBER:lock_wait:float} \s*Rows_sent: %{NUMBER:results:int} \s*Rows_examined: %{NUMBER:scanned:int}\nSET timestamp=%{NUMBER:timestamp};\n%{GREEDYDATA:query};',
        #'message' , '(?m)^# User@Host: %{USER:user}\[[^\]]+\] @ %{WORD} \[%{IP:ip_addr}?]%{SPACE}Id:%{SPACE}%{NUMBER:idd}\n# Query_time: %{NUMBER:duration} \s*Lock_time: %{NUMBER:lock_wait} \s*Rows_sent: %{NUMBER:results} \s*Rows_examined: %{NUMBER:scanned}\nSET timestamp=%{NUMBER:timestamp};\n%{GREEDYDATA:query};',
        'message' , '(?m)^# User@Host: %{USER:user}\[[^\]]+\] @ %{WORD} \[%{IP:ip_addr}?]%{SPACE}Id:%{SPACE}%{NUMBER:idd}\n# Query_time: %{NUMBER:duration:float} \s*Lock_time: %{NUMBER:lock_wait:float} \s*Rows_sent: %{NUMBER:results:int} \s*Rows_examined: %{NUMBER:scanned:int}\nuse%{SPACE}%{WORD:database};\nSET timestamp=%{NUMBER:timestamp};\n%{GREEDYDATA:query};',
        'message' , '(?m)^# User@Host: %{USER:user}\[[^\]]+\]%{SPACE}@%{SPACE}\[%{IP:ip_addr}?]%{SPACE}Id:%{SPACE}%{NUMBER:idd}\n# Query_time: %{NUMBER:duration:float} \s*Lock_time: %{NUMBER:lock_wait:float} \s*Rows_sent: %{NUMBER:results:int} \s*Rows_examined: %{NUMBER:scanned:int}\nuse%{SPACE}%{WORD:database};\nSET timestamp=%{NUMBER:timestamp};\n%{GREEDYDATA:query};',
        'message' , '(?m)^# User@Host: %{USER:user}\[[^\]]+\]%{SPACE}@%{SPACE}\[%{IP:ip_addr}?]%{SPACE}Id:%{SPACE}%{NUMBER:idd}\n# Query_time: %{NUMBER:duration:float} \s*Lock_time: %{NUMBER:lock_wait:float} \s*Rows_sent: %{NUMBER:results:int} \s*Rows_examined: %{NUMBER:scanned:int}\nSET timestamp=%{NUMBER:timestamp};\n%{GREEDYDATA:query};'
      ]
      remove_tag => ["_grokparsefailure"]
    }
    date {
      match => [ "timestamp", "UNIX" ]
    }
  }

  if "discard-mysql-slowlog" in [tags] {
    drop{}
  }

}
output {
  #stdout { codec => rubydebug }
  elasticsearch {
    embedded => false
    host => "127.0.0.1"
    protocol => transport
  }

}
```

**Comment by mihaiplesa** [comment] 2015-05-28 15:53
Also happens to us.

output {
    elasticsearch {
        cluster => "logstash"
        host => "elasticsearch.cluster.example.com"
    }
}

When logstash starts up, the DNS entry is not available yet and we get the exceptions.

After the entry is becomes available, logstash does not resolve it, still throws exceptions.

If we restart logstash after it is available, it works.

DNS resolution has to be performed more often in this case.

**Comment by skuran** [comment] 2015-06-23 12:06
I am facing the same problem. logstash-1.4.2 and elasticsearch 1.1.1. logstash stops to send logs to ES after running months. The message in the log: message=>"Failed to flush outgoing items", :outgoing_count=>158, :exception=>#<NameError: no method 'type' for arguments
Tons of the same line. When logstash is killed and started again, problem goes away until the next time.

**Comment by drocsid** [comment] 2015-07-01 23:55
I'm having a similar issue here on logstash 1.5.1:

{:timestamp=>"2015-06-30T12:11:17.093000-0600", :message=>"Failed to flush outgoing items", :outgoing_count=>12, :exception=>#<NameError: no method 'type' for arguments (org.jruby.RubyArray) on Java::OrgElasticsearchActionIndex::IndexRequest>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.8-java/lib/logstash/outputs/elasticsearch/protocol.rb:261:in `build_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.8-java/lib/logstash/outputs/elasticsearch/protocol.rb:222:in `bulk'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.8-java/lib/logstash/outputs/elasticsearch/protocol.rb:221:in `bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.8-java/lib/logstash/outputs/elasticsearch.rb:466:in `submit'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.8-java/lib/logstash/outputs/elasticsearch.rb:465:in `submit'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.8-java/lib/logstash/outputs/elasticsearch.rb:490:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.8-java/lib/logstash/outputs/elasticsearch.rb:489:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1341:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:193:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:112:in `buffer_initialize'", "org/jruby/RubyKernel.java:1511:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:110:in `buffer_initialize'"], :level=>:warn}

I found some related items:

https://logstash.jira.com/browse/LOGSTASH-2107
https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/138

**Comment by madAndroid** [comment] 2015-07-06 08:09
I'm seeing the same issue in our vagrant setup: we have three boxes, one of which, the second one, runs an ELK stack .. same as @mihaiplesa, when DNS for the ES node doesn't resolve, we see the buffer fill up with:
```
{:timestamp=>"2015-07-06T08:04:23.420000+0000", :message=>"Got error to send bulk of actions: elasticsearch.service.consul: Name or service not known", :level=>:error}
```
However, even when DNS is then active, the buffer doesn't appear to clear down, even though ES is available after all three boxes are up and configured.. the only way I've found to completely resolve the issue so far is to completely remove logstash from all three boxes and re-install - then the plugin appears to start working when ES is available immediately upon install.

Is there any way to manually flush the buffer? Seeing lots of:

```
{:timestamp=>"2015-07-06T08:06:26.301000+0000", :message=>"Failed to flush outgoing items", :outgoing_count=>1, :exception=>#<Manticore::ResolutionFailure: elasticsearch.service.consul>,
```
even when the host is then available, is still seems that there is no hostname resolution, almost as if these messages are never able to be cleared from the buffer.

**Comment by madAndroid** [comment] 2015-07-06 08:11
> However, even when DNS is then active, the buffer doesn't appear to clear down, even though ES is available after all three boxes are up and configured.. the only way I've found to completely resolve the issue so far is to completely remove logstash from all three boxes and re-install - then the plugin appears to start working when ES is available immediately upon install.

Further to this: it seems as though at some point logstash does kick in, as I'm seeing entries in the stdout log, but the buffer still never seems to clear down.

**Comment by andrewvc** [comment] 2015-07-10 20:37
Part of the issue here is that `Stud::Buffer` is swallowing the actual exception class name. We need to figure this out now, but that definitely needs patching: I've opened a new issue for that here: https://github.com/jordansissel/ruby-stud/issues/21

**Comment by sayotte** [comment] 2015-08-14 13:39
Just observed this on logstash-1.5.3:
Got error to send bulk of actions: no method 'type' for arguments (org.jruby.RubyArray) on Java::OrgElasticsearchActionIndex::IndexRequest {:level=>:error}
Failed to flush outgoing items {:outgoing_count=>1, :exception=>#<NameError: no method 'type' for arguments (org.jruby.RubyArray) on Java::OrgElasticsearchActionIndex::IndexRequest>, :backtrace=>["/opt/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.5-java/lib/logstash/outputs/elasticsearch/protocol.rb:262:in `build_request'", "/opt/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.5-java/lib/logstash/outputs/elasticsearch/protocol.rb:223:in `bulk'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.5-java/lib/logstash/outputs/elasticsearch/protocol.rb:222:in `bulk'", "/opt/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.5-java/lib/logstash/outputs/elasticsearch.rb:519:in `submit'", "/opt/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.5-java/lib/logstash/outputs/elasticsearch.rb:518:in `submit'", "/opt/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.5-java/lib/logstash/outputs/elasticsearch.rb:543:in `flush'", "/opt/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.5-java/lib/logstash/outputs/elasticsearch.rb:542:in `flush'", "/opt/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1341:in `each'", "/opt/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:193:in `buffer_flush'", "/opt/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:159:in `buffer_receive'", "/opt/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.5-java/lib/logstash/outputs/elasticsearch.rb:508:in `receive'", "/opt/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/outputs/base.rb:88:in `handle'", "(eval):191:in `output_func'", "/opt/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/pipeline.rb:244:in `outputworker'", "/opt/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/pipeline.rb:166:in `start_outputs'"], :level=>:warn}

Here's my output config:
output {
  stdout { codec => rubydebug }
  elasticsearch {
    protocol => transport
    port => 9300
    host => "172.17.0.26"
  }
}

ES is 1.7.1

I just got this working last night, watched it for a while before going to bed, then found it broken in the morning. Both processes are running in Docker containers.

**Comment by talevy** [comment] 2015-08-14 16:33
@sayotte from the error, it seems that your `type` field is not a string, but actually an array type.

would you mind opening a new issue for this specifically, and share any relevant filters you are applying to modify the fields?

thanks!

**Comment by andrewvc** [comment] 2015-10-26 22:25
This error is certainly being caused by the type field being somehow set to a non-string value. #283 will fix that once merged (and will be part of LS2.0). Closing this issue given that.

**Closed by andrewvc** 2015-10-26 22:25 UTC
Labels: needs reviewing, question
