### ISSUE TITLE
LS Elasticsearch output with http hangs without logging anything if ES is "kill -9"ed

### ISSUE THREAD

**Issue by astefan** [logstash-plugins/logstash-output-elasticsearch#260] opened 2015-10-01 09:16 UTC
If ES is being started back up, Logstash will not start sending data. It needs a restart.

**Comment by jordansissel** [comment] 2015-10-02 13:50
We (@astefan, et al) dug into this, and our suspicion is that `kill -9` leaves the network stack abandoned, so Logstash (the client) is never sent an RST nor FIN, or something to the effect that the network connection is left open.

I'm going to try and reproduce, but overall our hypothesis is that this is caused by internally having timeouts disabled (due to a recent bug fix for a different problem). Will investigate making this configurable also.

**Comment by jordansissel** [comment] 2015-10-02 13:54
The original report for this issue was done offline and was using Azure as the platform, so I can't accurately reproduce this right now.

Still, I'll work on adding timeouts so we can explore the problem further.

**Comment by andrewvc** [comment] 2016-12-20 21:17
This has been fixed in #270 and subsequent refactors.

**Closed by andrewvc** 2016-12-20 21:17 UTC
Labels: bug
