### ISSUE TITLE
HTTP Sniffing should do role detection / selection

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [logstash-plugins/logstash-output-elasticsearch#699] opened 2017-11-01 14:45 UTC
Currently there is no way to auto-discover targets on an Elasticsearch cluster filtered by a set of node roles.

This would be useful for example, when we know the master hostnames, but coordinating nodes auto-scale and are generally ephemeral, in docker or cloud environments, etc.

As reference, The NEST client [supports role detection](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/sniffing-role-detection.html)

**Comment by jordansissel** [comment] 2017-11-01 17:14
Closing this as a duplicate of one or both of these:
* https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/599
* https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/438

**Closed by jordansissel** 2017-11-01 17:14 UTC

**Comment by jordansissel** [comment] 2017-11-01 17:16
> coordinating nodes auto-scale and are generally ephemeral

I'm open to a separate ticket where we discuss merits, if any, of why a user would direct the ES output to only use coordinating nodes.

**Comment by PhaedrusTheGreek** [comment] 2017-11-01 17:21
Possibly never, so it seems like a more generic option like node attributes would work.
