### ISSUE TITLE
manticore timeout terminates logstash 2.0.0 instance

### ISSUE THREAD

**Issue by vlaadbrain** [logstash-plugins/logstash-output-elasticsearch#304] opened 2015-11-11 20:00 UTC
logstash-2.0.0 with the following output config
plugin version: logstash-output-elasticsearch (2.1.2)
The hosts below are pingable and i can curl http://$host:9200/; every host returns status: 200

```
elasticsearch {
    action => "index"
    hosts => ["host1", "host2", "host3"]
    document_id => "%{anonid}"
    index => "logstash-%{type}-%{+YYYY.MM.dd}"
    max_retries => 10
    retry_max_interval => 5
    retry_max_items => 100
    flush_size => 100
    timeout => 25
    workers => 10
}
```

gets me an error like so and the process crashes...

```
Manticore::SocketTimeout: Read timed out
   initialize at /opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.4.4-java/lib/manticore/response.rb:35
         call at org/jruby/RubyProc.java:271
         call at /opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.4.4-java/lib/manticore/response.rb:70
    call_once at /opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.4.4-java/lib/manticore/response.rb:245
         code at /opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.4.4-java/lib/manticore/response.rb:148
perform_request at /opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/http/manticore.rb:71
         call at org/jruby/RubyProc.java:271
perform_request at /opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/base.rb:191
perform_request at /opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/http/manticore.rb:54
perform_request at /opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/client.rb:119
         bulk at /opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/actions/bulk.rb:87
         bulk at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch/http_client.rb:56
       submit at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch.rb:353
  synchronize at org/jruby/ext/thread/Mutex.java:149
       submit at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch.rb:350
  retry_flush at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch.rb:514
     register at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch.rb:294
```

**Comment by CheeriosJo** [comment] 2015-12-10 19:38
I am also getting the same error for file input and http output on logstash 2.0.0

**Comment by LeoShi** [comment] 2016-03-28 06:39
I got the same issue with logstash-2.2. It's weird that this is only happened after a few days running of logstash. After restart the process, the problem is gone.

	{:timestamp=>"2016-03-28T14:06:20.902000+0800", :message=>"Attempted to send a bulk request to Elasticsearch configured at '[\"http://host1:9200/\"]', but Elasticsearch appears to be unreachable or down!", :client_config=>{:hosts=>["http://host1:9200/"], :ssl=>nil, :transport_options=>{:socket_timeout=>0, :request_timeout=>0, :proxy=>nil, :ssl=>{}}, :transport_class=>Elasticsearch::Transport::Transport::HTTP::Manticore, :logger=>nil, :tracer=>nil, :reload_connections=>false, :retry_on_failure=>false, :reload_on_failure=>false, :randomize_hosts=>false}, :error_message=>"Connection timed out", :class=>"Manticore::SocketException", :level=>:error}

**Comment by hkarpf** [comment] 2016-05-13 00:31
Same issue here.

**Comment by hkarpf** [comment] 2016-05-19 13:35
More details, I think this is due to Java not following the keepalive settings in the OS and a Firewall between the logstash box and elasticsearch cluster killing the connections (if idle) if data doesn't flow through the connection.

**Comment by hkarpf** [comment] 2016-05-19 13:43
@LeoShi @vlaadbrain Can you confirm that there is a firewall device between your logstash and elasticsearch cluster?

**Comment by hkarpf** [comment] 2016-05-19 14:44
Quick update.  For others who run into this issue, even though Manticore/Logstash does not set keepalive_so settings on connections, the Elasticsearch cluster will.  So to fix this issue, set the net.ipv4..tcp_keepalive* settings according to this article to something that makes sense in your environment, in our case it was to 30 minutes.
http://knowledgebase.progress.com/articles/Article/000044970

Just implemented this change, and will report back in a few hours.

**Comment by hkarpf** [comment] 2016-05-19 16:12
Happy to report, this appears to have fixed my issue, see my previous comment.

**Comment by vlaadbrain** [comment] 2016-05-28 20:15
@hkarpf - sorry haven't had a chance to confirm, will reply when confirmed, that may take some time though.

**Comment by evacao1225** [comment] 2016-10-21 04:28
@hkarpf  - I also ran into this issue after Logstash running several hours. Great to see your comments. You mentioned that setting net.ipv4.tcp_keepalive_time to 30 mins addressed your issue. I have some questions. Do you mean setting that in the server that the Logstash is, or the Elasticsearch is? Only net.ipv4.tcp_keepalive_time, or other two settings(tcp_keepalive_intvl and tcp_keepalive_probes) are also needed to set? 

I have been bothered for several days by this issue. Thanks so much for your help.

**Comment by hkarpf** [comment] 2016-11-03 18:14
@evacao1225 Well changing these settings helped for a bit, however what really helped was reducing the number of workers in logstash so open connections kept getting used.  E.g. I went from 24 workers (so some threads would sit idle for a very long time) to 4, so now the 4 open logstash connections get utilized more often.  I also noticed from the Logstash 5.0 release info: https://www.elastic.co/blog/logstash-5-0-0-released, that they implemented:

> Other enhancements include a new connection pool to efficiently reuse connections to Elasticsearch, exponential backoff for connection retries, and better handling for sniffing.

**Comment by andrewvc** [comment] 2016-12-20 17:25
This was fixed in a more general sense in the latest version of this output which no longer needs output workers (it is a `shared`) plugin type and has a smarter connection management algorithm.

Closing this issue for now. Please  re-open if you have further issues.

**Closed by andrewvc** 2016-12-20 17:25 UTC
