### ISSUE TITLE
Delete action with HTTP protocol

### ISSUE THREAD

**Issue by ronlepper** [logstash-plugins/logstash-output-elasticsearch#195] opened 2015-07-08 22:03 UTC
I am currently trying to process the deletion of documents from my ElasticSearch index using the logstash-output-elasticsearch plugin configured to use the http protocol.  The bulk request sent to elasticsearch from the output plugin fails with the error below.

It looks like it is sending the action and the source if source exists.  The source is the event as far as I can tell. But for delete actions in the bulk api, there shouldn't be any source, which is why the error is coming back.  Maybe there is some value in the event that I need to set that I am missing?

HttpClient in protocol.rb

    def bulk(actions)
        bulk_response = @client.bulk(:body => actions.collect do |action, args, source|
            if source
                next [ { action => args }, source ]
            else
                next { action => args }
            end
        end.flatten)
    
        self.class.normalize_bulk_response(bulk_response)
    end # def bulk

For the node and transport protocol, it looks like it is checking the action and not adding source for delete actions.

I am using logstash version 1.5.2 with ElasticSearch version 1.6.0.

        {:timestamp=>"2015-07-08T10:57:06.360000-0700", :message=>"Got error to send bulk of actions: [500] {\"error\":\"IllegalArgumentExce
    ption[Malformed action/metadata line [2], expected START_OBJECT or END_OBJECT but found [null]]\",\"status\":500}", :level=>:error}
    :timestamp=>"2015-07-08T10:57:06.364000-0700", :message=>"Failed to flush outgoing items", :outgoing_count=>1, :exception=>#<Elasti
    csearch::Transport::Transport::Errors::InternalServerError: [500] {"error":"IllegalArgumentException[Malformed action/metadata line 
    [2], expected START_OBJECT or END_OBJECT but found [null]]","status":500}>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems
    /elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/base.rb:135:in `__raise_transport_error'", "/opt/logstash/vend
    or/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/base.rb:227:in `perform_request'", "/o
    pt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/http/manticore.rb:54:i
    n `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/client.
    rb:119:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.12/lib/elasticsearch/api/actions/bul
    k.rb:80:in `bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.1-java/lib/logstash/outputs/elasti
    csearch/protocol.rb:103:in `bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.1-java/lib/logstas
    h/outputs/elasticsearch.rb:505:in `submit'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.1-java/li
    b/logstash/outputs/elasticsearch.rb:529:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:219:
    in `buffer_flush'", "org/jruby/RubyHash.java:1341:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffe
    r.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:193:in `buffer_flush'", "/op
    t/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:112:in `buffer_initialize'", "org/jruby/RubyKernel.java:1511:
    in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:110:in `buffer_initialize'"], :level=>:warn}

**Comment by ronlepper** [comment] 2015-07-08 22:06
I was able to get the deletes working correctly by updating the plugin to  check the action and source, but not sure if that's the correct approach.

    def bulk(actions)
		bulk_response = @client.bulk(:body => actions.collect do |action, args, source|
			if source and action != 'delete'
				next [ { action => args }, source ]
			else
				next { action => args }
			end
		end.flatten)
    
		self.class.normalize_bulk_response(bulk_response)
    end # def bulk

**Comment by klingsor83** [comment] 2015-07-09 20:23
I have the same error with logstash 1.5.2 and elasticsearch 1.6.0

**Comment by sergioschena** [comment] 2015-07-20 08:47
I have the same error too. According to the ES `bulk` API after a `delete` command no content has to be specified. Please solve this. It is very important.

**Comment by naro** [comment] 2015-08-13 08:00
Same here, it is not possible to delete documents because of the source is present. My "hotfix" is for [submit method](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch.rb#L539) and removes event in case of delete action.

```ruby
es_actions = actions.map { |a, doc, event| [a, doc, a=="delete" ? nil : event.to_hash] }
```
but removing the source in HTTPClient.bulk seems to be better approach


Without the fix, HTTP body it looks like this:
```
POST /_bulk
{"delete":{"_id":"tester","_index":"test-index","_type":"mytype","_routing":null}}
{"@version":"1","@timestamp":"2015-08-13T06:10:59.713Z","type":"mytype"}
```
which raises in Elastic:
```
{
   "error": "IllegalArgumentException[Malformed action/metadata line [2], expected START_OBJECT or END_OBJECT but found [VALUE_STRING]]",
   "status": 500
}
```

**Comment by andrewvc** [comment] 2015-08-17 12:20
Hey guys, I'll take a look at this soon. We'll be changing the default protocol to HTTP soon and this will definitely need to be fixed first: https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/150

**Comment by imadulhaque** [comment] 2015-09-25 19:30
Hi @andrewvc  any idea when this fix will be in? We are close to release now, this can really put us in difficult situation if we don't have this fixed anytime soon.

**Comment by andrewvc** [comment] 2015-09-25 19:34
@imadulhaque unfortunately we don't have a timeline for this at the moment. If you'd like to submit a pull request that could greatly help expedite a release. Our next release of this plugin will be for LS2.0, which will hopefully be in the next few weeks.

If you urgently need a fix I recommend forking this plugin, patching it, and using that version locally.

**Comment by imadulhaque** [comment] 2015-11-02 18:17
@andrewvc any updates on this? Is it fixed in LS 2.0?

**Comment by suyograo** [comment] 2015-11-02 18:24
@imadulhaque nope

**Comment by imadulhaque** [comment] 2015-11-02 18:29
@suyograo any plans when can this be fixed? is there a worked around for this?

**Comment by andrewvc** [comment] 2015-11-02 20:41
@imadulhaque we'd like to get this in after the refactor work in #291 , which we're hoping to release sometime this week if all goes well.

**Comment by imadulhaque** [comment] 2015-11-02 20:58
ok thanks @andrewvc.

**Comment by yoitsro** [comment] 2015-12-10 15:02
Any news on this @andrewvc?

**Comment by andrewvc** [comment] 2015-12-10 15:26
@yoitsro @imadulhaque are you guys still experiencing this? I thought we fixed it in the latest versions of the ES output. Can you confirm the version you guys are using if this is still a problem?

**Comment by sureshadapa** [comment] 2015-12-14 09:55
I am trying with ES-2.1.0 and logstash2.1.1

# file: contacts-index-logstash.conf
input {
    jdbc {
        # Postgres jdbc connection string to our database, mydb
        jdbc_connection_string => "jdbc:postgresql://localhost:5432/postgres"
        # The user we wish to execute our statement as
        jdbc_user => "postgres"
        jdbc_password => "suresh"
	jdbc_validate_connection => true
        # The path to our downloaded jdbc driver
        jdbc_driver_library => "E:\Apps\elasticsearch\logstash-1.5.3\lib\postgresql-9.4-1201.jdbc4.jar"
        # The name of the driver class for Postgresql
        jdbc_driver_class => "org.postgresql.Driver"
        # our query
        statement => "SELECT * from contacts"
    }
}
output {

#cleanup index
    elasticsearch {
        action => "delete"
        protocol => http
        index => "contacts"
        host => "localhost"
    }
#load fresh data into index
#    elasticsearch {
#        protocol => http
#        index => "contacts"
#        document_type => "contact"
#        document_id => "%{uid}"
#        host => "localhost"
#    }

}

**Comment by yoitsro** [comment] 2015-12-14 10:46
@andrewvc Why do you think this was fixed? Looking back through this thread, there seems to be the same solution posted multiple times, but no PRs. And looking at code on master, judging by this line: https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/http_client.rb#L59, nothing's been fixed.

**Comment by yoitsro** [comment] 2015-12-14 10:50
In fact, here we are: https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/328

I will add tests once I get a moment, but as far as the logic goes, does this make sense?

**Comment by sureshadapa** [comment] 2015-12-14 13:02
I still see the problem with ES-2.1.0 and logstash2.1.1

**Comment by andrewvc** [comment] 2015-12-14 17:29
@yoitsro apologies, I was just pulling from my memory. I'll try and fix this tomorrow. I agree this is a high priority bug.

**Comment by yoitsro** [comment] 2015-12-14 20:53
@andrewvc Thanks! Much appreciated.

**Comment by andrewvc** [comment] 2015-12-17 21:47
This is now merged into master and part of the latest release of this plugin (but not yet Logstash as a distro)

**Closed by andrewvc** 2015-12-17 21:47 UTC
Labels: bug

**Comment by yoitsro** [comment] 2015-12-18 19:00
@andrewvc Good job! Thank you!

**Comment by gammaliu** [comment] 2016-04-06 07:13
I am using logstash-2.3 , but "delete" still doesn't work.  Are there any suggestions to figure out what's wrong?

**Comment by imadulhaque** [comment] 2016-05-06 19:10
seems like "delete" is broken and not working any more. I am using 2.2.2. Any ideas how to fix it? Should I go back to 2.1.1 with ES 2.2.1 that I am using?

**Comment by imadulhaque** [comment] 2016-05-08 14:45
@andrewvc can you please confirm which version of logstash do we need to use to have this fix?

**Comment by andrewvc** [comment] 2016-05-09 15:52
@imadulhaque I'm not sure exactly when it landed but I just confirmed that delete works with the latest 2.3.2 and 2.2.1 running the following on an empty Elasticsearch instance.

```
# Insert some documents numbered 1, 2, 3, ...
bin/logstash -w 1 -e 'input { generator { count => 100 } } output { stdout { codec => rubydebug} elasticsearch { document_id => "%{sequence}" } }'

# Test that there are docs
curl 'http://localhost:9200/log*/_search?pretty&size=1'

# Delete them all
bin/logstash -w 1 -e 'input { generator { count => 100 } } output { stdout { codec => rubydebug} elasticsearch { action => delete document_id => "%{sequence}" } }'

# Test that there are no docs
curl 'http://localhost:9200/log*/_search?pretty&size=1'
```


@gammaliu can you share your config on https://discuss.elastic.co/c/logstash ? It's most likely a configuration error. We can help you troubleshoot it there.

**Comment by imadulhaque** [comment] 2016-05-10 12:50
I have tried 2.3.2 and earlier versions but for some reason, data getting deleted is still there in elasticsearch and in addition a new record is created without data in it. I believe this new record is created by the delete event. 

`{
            "_index": "users_index",
            "_type": "%{[doc][type]}",
            "_id": "3f7cfd671d5d91400442e819af087346",
            "_score": 1,
            "_source": {
               "@version": "1",
               "@timestamp": "2016-05-10T12:44:34.334Z",
               "tags": [
                  "users"
               ]
            }
         }`

All of this was working fine until recently. Could it be due to any specific version of logstash-input-couchdb_changes plugin that gets installed. since I am just running command logstash-plugin install logstash-input-couchdb_changes, it would be installing it from internet. Do I need to use an older/stable version of plugin? 
Will really appreciate your help.

Thanks,
Imad.

**Comment by Shifter2600** [comment] 2016-08-23 03:03
I understand 
elasticsearch {
protocol => http
index => "contacts"
document_type => "contact"
document_id => "%{uid}"
host => "localhost"

My question is can I have index looking at a group of indexes for that document_id?
by using index => "logstash-company-*" I need to make sure that I am only deleting the ID from a specific company and not others that may have that ID in existence.
