### ISSUE TITLE
504 as retryable code

### ISSUE THREAD

**Issue by rparkhunovsky** [logstash-plugins/logstash-output-elasticsearch#578] opened 2017-03-24 07:00 UTC
What is the concern that 504 code is not included into the list of retryable ones? Is it feasible to allow 504 to be retried?
Since requests are dropped is there another way to prevent this from happening?
```
[2017-03-24T05:48:38,668][ERROR][logstash.outputs.elasticsearch] Got a bad response code from server, but this code is not considered retryable. Request will be dropped {:code=>504, :response_body=>""}
```

- ES and Logstash : 5.2.2
- Version: 6.2.6  
- Operating System:Amazon Linux

**Comment by untergeek** [comment] 2017-03-24 16:34
A 504 is a gateway timeout error.  This is not a code that Elasticsearch will ever send.  This implies that Elasticsearch is behind a load balancer (ELB I presume, since you specify Amazon Linux).  Logstash has no idea what kind of gateway/LB is being used.  There's no way to know if it's intermittent, or going to be persistent.  The way Logstash will address this in the future is with a dead-letter queue (DLQ).  We will not likely change the code to accept a 504 as a retry-able response.

On a different note, a 504 error tends to be delivered after a _very_ long timeout, like 60 seconds or more.  That much delay in Logstash sending data will cause all kinds of backups.  That is definitely less than ideal.  Again, our solution is to have a DLQ to catch these events so they can be re-ingested after whatever caused the outage has been corrected.  Infinite retry on a 504 is otherwise just likely to cause Logstash to back up, infinitely.

**Comment by untergeek** [comment] 2017-03-24 16:45
It's up for discussion, however: https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/572

**Comment by jordansissel** [comment] 2017-03-24 16:45
This is somewhat of a dup of https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/572

The problem is that Logstash targets exactly Elasticsearch, and Elasticsearch will never return a 504 error code, so we don't look for it.

#572 will work on a resolution for this, but with a strong caveat that if you are pointing the elasticsearch output at an entity that does not behave like Elasticsearch, then we cannot make any guarantees about the result.

**Comment by jordansissel** [comment] 2017-03-24 16:45
Closing in favor of #572

**Closed by jordansissel** 2017-03-24 16:45 UTC
