### ISSUE TITLE
Logstash “Elasticsearch” output plugin does not support SSL client certificates

### ISSUE THREAD

**Issue by bozzerreaneaux** [logstash-plugins/logstash-output-elasticsearch#672] opened 2017-09-13 07:54 UTC
Plugin version: v7.4.0
Released on: 2017-08-21

Hello team,

This is more of a feature request and not an issue..

I've noticed the Elasticsearch output plugin does not offer configuration for client certificate so that the Logstash pipeline can also authenticate with a client certificate.

Here's my case: I am evaluating X-Pack and PKI realms for a centralized logging POC solution for our company. My intention was to implement mutual authentication between beats and Logstash and between Logstash and Elasticsearch .

I would like to have separate Beats and Logstash instance per each application server so that I can later configure role based access for each Logstash pipeline and isolate the data from different applications(projects)

I was surprised to learn that the elasticsearch output configuration doesn't offer client certificate options but only options to configure certification authority (either cacert path or in java truststore) to verify the Elasticsearch server cert.

Is this something that I can possibly implement by editing  \vendor\bundle\jruby\1.9\gems\logstash-output-elasticsearch-7.3.8-java\lib\logstash\outputs\elasticsearch\**http_client_builder.rb** or any other file?

**Comment by Nrezinorn** [comment] 2017-09-19 23:29
+1 for this features please.  I am fumbling trying to get this working on a dev machine myself.

**Comment by jordansissel** [comment] 2017-09-20 00:34
We will work on this feature. No ETA is available. No further +1s are
necessary.

**Comment by hex2a** [comment] 2017-09-20 09:49
according to the documentation, this should be possible using the `keystore` parameter?

https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-keystore

**Comment by sadok-f** [comment] 2017-12-13 11:04
+1

**Comment by jsvd** [comment] 2018-05-17 10:39
closing as duplicate of https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/672

**Comment by carldunham** [comment] 2018-06-15 19:20
Wait, this IS #672

**Comment by berndvdveen** [comment] 2018-09-12 11:42
Is it possible to give an ETA for the implementation of this feature?

**Closed** 2023-03-10 16:51 UTC
