### ISSUE TITLE
URI host empty but is configured

### ISSUE THREAD

**Issue by lendoly** [logstash-plugins/logstash-output-elasticsearch#629] opened 2017-08-01 11:21 UTC
Hello I'm having troubles with the configuration for the output.

my stack is:
- logstash: 5.5.1
- elasticsearch:  5.5.1
- output-elasticsearch: 7.3.7

I have all in containers and the logstash container is linked to the node_master_1 container (which is a master node of my elastisearch stack)
```
input {
    beats {
        port => 5000
    }
}

filter {
   # DO things
}

output {
    if [type] == "A" {
        elasticsearch {
            hosts => [ "http://node_master_1:9200" ]
            index => "errors-%{+YYYY.MM.dd}"
            user => "logstash"
            password => "XXXX"
        }
    }
    if [type] == "B" {
        elasticsearch {
            hosts => [ "http://node_master_1:9200" ]
            index => "info-%{+YYYY.MM.dd}"
            user => "logstash"
            password => "XXXX"
        }
    }
}
```

but for some reason I'm getting the next trace in my logstash output:

```
[2017-08-01T11:09:18,892][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>#<Java::JavaNet::URI:0x6cc84a68>, :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://logstash:XXXX@:9200/][Manticore::ClientProtocolException] URI does not specify a valid host name: http:/"}
[2017-08-01T11:09:18,944][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://logstash:XXXX@:9200/, :path=>"/"}
[2017-08-01T11:09:18,944][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://logstash:XXXX@:9200/, :path=>"/"}
[2017-08-01T11:09:18,944][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://logstash:XXXX@:9200/, :path=>"/"}
[2017-08-01T11:09:18,946][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>#<Java::JavaNet::URI:0x1b25cc3f>, :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://logstash:XXXX@:9200/][Manticore::ClientProtocolException] URI does not specify a valid host name: http:/"}
[2017-08-01T11:09:18,946][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>#<Java::JavaNet::URI:0x1aa75691>, :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://logstash:XXXX@:9200/][Manticore::ClientProtocolException] URI does not specify a valid host name: http:/"}
[2017-08-01T11:09:18,946][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>#<Java::JavaNet::URI:0x3d549715>, :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://logstash:XXXX@:9200/][Manticore::ClientProtocolException] URI does not specify a valid host name: http:/"}
[2017-08-01T11:09:18,993][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://logstash:XXXX@:9200/, :path=>"/"}
[2017-08-01T11:09:18,994][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>#<Java::JavaNet::URI:0x31e6c438>, :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://logstash:XXXX@:9200/][Manticore::ClientProtocolException] URI does not specify a valid host name: http:/"}
[2017-08-01T11:09:19,077][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://logstash:XXXX@:9200/, :path=>"/"}
[2017-08-01T11:09:19,077][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://logstash:XXXX@:9200/, :path=>"/"}
[2017-08-01T11:09:19,078][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://logstash:XXXX@:9200/, :path=>"/"}
[2017-08-01T11:09:19,078][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://logstash:XXXX@:9200/, :path=>"/"}
[2017-08-01T11:09:19,078][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://logstash:XXXX@:9200/, :path=>"/"}
[2017-08-01T11:09:19,078][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>#<Java::JavaNet::URI:0x5ace2764>, :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://logstash:XXXX@:9200/][Manticore::ClientProtocolException] URI does not specify a valid host name: http:/"}
[2017-08-01T11:09:19,078][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://logstash:XXXX@:9200/, :path=>"/"}
[2017-08-01T11:09:19,079][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>#<Java::JavaNet::URI:0x7e47f511>, :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://logstash:XXXX@:9200/][Manticore::ClientProtocolException] URI does not specify a valid host name: http:/"}
[2017-08-01T11:09:19,079][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>#<Java::JavaNet::URI:0x63586cce>, :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://logstash:XXXX@:9200/][Manticore::ClientProtocolException] URI does not specify a valid host name: http:/"}
[2017-08-01T11:09:19,079][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>#<Java::JavaNet::URI:0x46fed58b>, :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://logstash:XXXX@:9200/][Manticore::ClientProtocolException] URI does not specify a valid host name: http:/"}
[2017-08-01T11:09:19,079][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>#<Java::JavaNet::URI:0xe5e7299>, :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://logstash:XXXX@:9200/][Manticore::ClientProtocolException] URI does not specify a valid host name: http:/"}
[2017-08-01T11:09:19,079][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>#<Java::JavaNet::URI:0x4ade209e>, :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://logstash:XXXX@:9200/][Manticore::ClientProtocolException] URI does not specify a valid host name: http:/"}
[2017-08-01T11:09:19,151][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://logstash:XXXX@:9200/, :path=>"/"}
[2017-08-01T11:09:19,151][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://logstash:XXXX@:9200/, :path=>"/"}
[2017-08-01T11:09:19,152][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>#<Java::JavaNet::URI:0xf48516>, :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://logstash:XXXX@:9200/][Manticore::ClientProtocolException] URI does not specify a valid host name: http:/"}
[2017-08-01T11:09:19,152][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>#<Java::JavaNet::URI:0x390a113b>, :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://logstash:XXXX@:9200/][Manticore::ClientProtocolException] URI does not specify a valid host name: http:/"}
[2017-08-01T11:09:20,454][DEBUG][logstash.pipeline        ] Pushing flush onto pipeline
```

The most strange thing is that this is for my acceptant environment, in prod I have working all in 5.2 with the same configuration and I'm not having theses problems.

Things that I already checked: 
- all the output has the same config
- no misspell 
- if I change the `hosts` still not use them
- the ports are well configured

**Comment by lendoly** [comment] 2017-08-01 14:12
after checking few things the problem is the underscores in the configuration

**Comment by ntim** [comment] 2018-02-01 07:05
I think this is a duplicate of #400

**Comment by jsvd** [comment] 2018-05-17 10:36
closing as duplicate of #400

**Closed by jsvd** 2018-05-17 10:36 UTC
