### ISSUE TITLE
Logstash not recovering if NIC is shutdown then restored while using DNS names

### ISSUE THREAD

**Issue by n0othing** [logstash-plugins/logstash-output-elasticsearch#479] opened 2016-09-19 15:20 UTC
Logstash errors out and never recovers whenever the NIC it's using is shutdown and then restarted.  It seems like this only happens if using a hostname in the `hosts =>` property instead of an IP address (eg, LS _will_ recover once network connectivity is restored).

(**Note**: The original issue was reproduced by disabling network services in the GUI (the equivalent of systemctl stop network). I was also able to use `nmcli device disconnect <interface>`).

To reproduce on my side I had a CentOS 7 VM running Logstash 2.4 (also tested in 2.3.2). The instance was using this config, pointed at ES running on my host.

```
input {
    stdin {}
}

output {
    elasticsearch {
        hosts => ["http://Robbies-MBP.fios-router.home:9200"]
    }
    stdout {
        codec => rubydebug
    }
}
```

I reduced Linux's `tcp_retries2` as it was taking too long to reproduce the behavior with the default of `15` (which can equate [to 13 - 30 minutes](http://linux.die.net/man/7/tcp)). You could also just set a low timeout property in the LS config `timeout => 5`.

```
# echo 1 > /proc/sys/net/ipv4/tcp_retries2
```

Then start Logstash and confirm things are working:

```
[esadmin@localhost logstash-2.4.0]$ bin/logstash -f logstash.conf 
Settings: Default pipeline workers: 2
Pipeline main started
Hello World!
{
       "message" => "Hello World!",
      "@version" => "1",
    "@timestamp" => "2016-09-14T16:37:29.904Z",
          "host" => "localhost.localdomain"
}
```

Disable the NIC on the LS VM:

```
# nmcli device disconnect enp0s3
Device 'enp0s3' successfully disconnected.
```

Now try to send an event:

```
Yo!

Attempted to send a bulk request to Elasticsearch configured at '["http://Robbies-MBP.fios-router.home:9200"]', but Elasticsearch appears to be unreachable or down! 

{:error_message=>"Connection timed out", :class=>"Manticore::SocketException", :level=>:error}
Attempted to send a bulk request to Elasticsearch configured at '["http://Robbies-MBP.fios-router.home:9200"]', but an error occurred and it failed! Are you sure you can reach elasticsearch from this machine using the configuration provided? {:error_message=>"Robbies-MBP.fios-router.home: unknown error", :error_class=>"Manticore::ResolutionFailure", :backtrace=>["/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/manticore-0.6.0-java/lib/manticore/response.rb:37:in `initialize'", "org/jruby/RubyProc.java:281:in `call'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/manticore-0.6.0-java/lib/manticore/response.rb:79:in `call'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/manticore-0.6.0-java/lib/manticore/response.rb:256:in `call_once'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/manticore-0.6.0-java/lib/manticore/response.rb:153:in `code'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.1.0/lib/elasticsearch/transport/transport/http/manticore.rb:84:in `perform_request'", "org/jruby/RubyProc.java:281:in `call'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.1.0/lib/elasticsearch/transport/transport/base.rb:257:in `perform_request'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.1.0/lib/elasticsearch/transport/transport/http/manticore.rb:67:in `perform_request'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.1.0/lib/elasticsearch/transport/client.rb:128:in `perform_request'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.1.0/lib/elasticsearch/api/actions/bulk.rb:93:in `bulk'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:53:in `non_threadsafe_bulk'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:38:in `bulk'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:38:in `bulk'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/common.rb:172:in `safe_bulk'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/common.rb:101:in `submit'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/common.rb:86:in `retrying_submit'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/common.rb:29:in `multi_receive'", "org/jruby/RubyArray.java:1653:in `each_slice'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/common.rb:28:in `multi_receive'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/output_delegator.rb:130:in `worker_multi_receive'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/output_delegator.rb:114:in `multi_receive'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:301:in `output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:301:in `output_batch'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:232:in `worker_loop'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:201:in `start_workers'"], :level=>:error}

Robbies-MBP.fios-router.home: unknown error {:class=>"Manticore::ResolutionFailure", :backtrace=>["/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/manticore-0.6.0-java/lib/manticore/response.rb:37:in `initialize'", "org/jruby/RubyProc.java:281:in `call'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/manticore-0.6.0-java/lib/manticore/response.rb:79:in `call'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/manticore-0.6.0-java/lib/manticore/response.rb:256:in `call_once'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/manticore-0.6.0-java/lib/manticore/response.rb:153:in `code'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.1.0/lib/elasticsearch/transport/transport/http/manticore.rb:84:in `perform_request'", "org/jruby/RubyProc.java:281:in `call'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.1.0/lib/elasticsearch/transport/transport/base.rb:257:in `perform_request'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.1.0/lib/elasticsearch/transport/transport/http/manticore.rb:67:in `perform_request'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.1.0/lib/elasticsearch/transport/client.rb:128:in `perform_request'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.1.0/lib/elasticsearch/api/actions/bulk.rb:93:in `bulk'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:53:in `non_threadsafe_bulk'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:38:in `bulk'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:38:in `bulk'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/common.rb:172:in `safe_bulk'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/common.rb:101:in `submit'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/common.rb:86:in `retrying_submit'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/common.rb:29:in `multi_receive'", "org/jruby/RubyArray.java:1653:in `each_slice'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/common.rb:28:in `multi_receive'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/output_delegator.rb:130:in `worker_multi_receive'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/output_delegator.rb:114:in `multi_receive'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:301:in `output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:301:in `output_batch'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:232:in `worker_loop'", "/home/esadmin/Desktop/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:201:in `start_workers'"], :level=>:warn}
Attempted to send a bulk request to Elasticsearch configured at '["http://Robbies-MBP.fios-router.home:9200"]', but an error occurred
```

The above errors will be repeated continuously even after restoring the interface `# nmcli device connect enp0s3`. LS needs to be killed and restarted to get things working again.

As mentioned, a valid workaround is to just use an IP address in the `hosts =>` parameter. When you do this, you'll see this error till network connectivity is restored (in which case, the event ships and everything's happy)

```
Yo!

...
Attempted to send a bulk request to Elasticsearch configured at '["http://192.168.1.194:9200"]', but Elasticsearch appears to be unreachable or down! {:error_message=>"Connection timed out", :class=>"Manticore::SocketException", :level=>:error}
Attempted to send a bulk request to Elasticsearch configured at '["http://192.168.1.194:9200"]', but Elasticsearch appears to be unreachable or down! {:error_message=>"Network is unreachable", :class=>"Manticore::SocketException", :level=>:error}
Attempted to send a bulk request to Elasticsearch configured at '["http://192.168.1.194:9200"]', but Elasticsearch appears to be unreachable or down! {:error_message=>"Network is unreachable", :class=>"Manticore::SocketException", :level=>:error}
...

// nmcli device connect enp0s3

{
       "message" => "Yo!",
      "@version" => "1",
    "@timestamp" => "2016-09-14T16:53:54.208Z",
          "host" => "localhost.localdomain"
}
```

**Comment by vaijab** [comment] 2016-10-05 15:33
I have this problem too. I use a load balancer in front of elasticsearch http endpoint. If there is a network glitch and logstash loses a connection to ES, logstash will never be able to reconnect.

**Comment by n0othing** [comment] 2016-11-16 23:29
Tested this today on 5.0 using the same steps--> the logged messages are different, but the observed behavior is the same. Logstash will indefinitely send health/revive checks, but will not automatically recover till restarted.

For now, 2 reasonable work arounds are:

- Add an entry to your host file
- Use IP addresses instead of DNS names in the `hosts =>` array.

**Comment by vaijab** [comment] 2016-11-17 10:17
@n0othing very annoying. I was going to try 5.0 version and was hoping that this issues will be fixed. Version 5.x has the monitoring API, which can be used to potentially detect when logstash stalls: https://www.elastic.co/guide/en/logstash/5.0/monitoring.html, but that's not ideal.

**Comment by jordansissel** [comment] 2016-11-29 21:51
@jsvd can you look into this?

**Comment by vaijab** [comment] 2016-11-29 21:53
It would be amazing if someone who knows the codebase could look into this issue. We've been struggling with our ELK stack for quite some time.

**Comment by jsvd** [comment] 2016-11-30 13:26
I've been playing today with logstash 2.4.1 and 5.0.2 with a ubuntu vm. My setup is:

operating system tweaks:

```
root@jsvd-VirtualBox:~# ifconfig 
enp0s3    Link encap:Ethernet  HWaddr 08:00:27:01:cf:9a  
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0

root@jsvd-VirtualBox:~# cat /etc/hosts | grep lan
10.0.2.15 my.es.lan

root@jsvd-VirtualBox:~# echo 1 > /proc/sys/net/ipv4/tcp_retries2
```

logstash config:

```
$ cat ../logstash-5.0.2/cfg
input { generator { } }
filter {
  sleep { time => 1 }
}
output {
  stdout { codec => rubydebug }
  elasticsearch { hosts => ["my.es.lan:9200" ] }
}
```

elasticsearch config:
```
network.host: _enp0s3_
```

With this setup I tested the following sequence:

```
1. start elasticsearch (`bin/elasticsearch`)
2. start logstash (`bin/logstash -f cfg -w 1 -b 1`)
3. wait for the first 5 or so events to be indexed
4. detach the interface (`nmcli device disconnect enp0s3`)
5. wait for logstash to produce exceptions and keep seeing them for about 10 seconds
6. reattach the interface (`nmcli device connect enp0s3`)
```

With this setup, both logstash 2.4.1 and 5.0.2 were able to reconnect. Outputs from logstash can be found [in this gist](https://gist.github.com/jsvd/619b67613cbe2802bc96600bc3d41e20)

**Comment by jsvd** [comment] 2016-11-30 16:55
I need to dig deeper, perhaps set up a dns server instead of just using a /etc/hosts entry

**Comment by n0othing** [comment] 2016-11-30 17:17
@jsvd yeah, you'll need to test/rely on your LAN's DNS. When I had host file entries, everything recovered/reconnected.

**Comment by vaijab** [comment] 2016-11-30 17:22
@jsvd we disabled java dns caching which seemed to help a little, but does not solve the issue entirely.

**Comment by jsvd** [comment] 2016-11-30 17:27
thanks for the confirmation, I'll do more tests, I already have dnsmasq set up.

**Comment by jsvd** [comment] 2016-12-02 15:47
new tests executed with logstash 5.0.2 and 2.4.1, after installing dnsmasq on ubuntu:

elasticsearch running locally bound to 10.0.2.15 and created the `es.lan` host entry on dnsmasq:

```
$ dig es.lan

; <<>> DiG 9.10.3-P4-Ubuntu <<>> es.lan
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7790
;; flags: qr aa rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;es.lan.				IN	A

;; ANSWER SECTION:
es.lan.			0	IN	A	10.0.2.15

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Dec 02 15:37:26 WET 2016
;; MSG SIZE  rcvd: 40
```

logstash config:

```
input { generator { } }
output {
  stdout { codec => rubydebug }
  elasticsearch { hosts => ["http://es.lan:9200" ] }
}
```

test sequences executed:

sequence 1:

```
1. start elasticsearch (`bin/elasticsearch`)
2. start logstash (`bin/logstash -f cfg`)
3. wait for the first 500 or so events to be indexed
4. detach the interface (`nmcli device disconnect enp0s3`)
5. wait for logstash to produce exceptions and keep seeing them for about 10 seconds
6. reattach the interface (`nmcli device connect enp0s3`)
```

sequence 2:

```
1. start elasticsearch (`bin/elasticsearch`)
2. start logstash (`bin/logstash -f cfg`)
3. wait for the first 500 or so events to be indexed
4. disable all interfaces (`ifconfig enp0s3 down && ifconfig lo down`)
5. wait for logstash to produce exceptions and keep seeing them for about 10 seconds
6. reattach the interface (`ifconfig enp0s3 up && ifconfig lo up`)
```

In both sequences with both logstash 2.4.1 and 5.0.2 the flow of events restarted after action `#6`

Can anyone else with this problem provide more information on their environment? I'm running out of ideas here, the only test I'm missing is using two different machines (1 for logstash, 1 for elasticsearch).

**Comment by n0othing** [comment] 2016-12-06 20:35
@jsvd I was only able to reproduce by using 2 separate hosts (my laptop (ES) pointed at bridged VM running Centos 7 (LS)).

**Comment by jsvd** [comment] 2017-03-27 17:56
I finally got around to test this a bit more. I was able to replicate this using 2 Centos VMs on Amazon:
VM1 has elasticsearch installed with port 9200 open
VM2 has logstash on it

on VM2 I reduced the code surface to just the manticore library logstash uses to send http requests.
I created a script that reproduced the failures 100% of the time [here](https://gist.githubusercontent.com/jsvd/2ed2d27a8277d6863c98e0b1af318856/raw/f7f5d4667449456050950a7a7e2f0c283afb17e5/gistfile1.txt)

To reproduce I need to disconnect the network card twice. Only during the second disconnect I see the issue.
One thing I notice during the reproduction is that Manticore throws a ResolutionFailure exception instead of a more normal HostUnreachable.
Another detail is that this issue occurs because only a separate thread is doing the requests. If a second thread executes another request on the same manticore client, it can unblock the situation.

Further investigation is now necessary, possible by stripping Manticore and using httpclient directly.

**Comment by jsvd** [comment] 2017-03-28 09:51
I can now replicate this issue using jruby only:

```ruby
java_import java.net.InetAddress

def lookup
  puts InetAddress.getByName("ec2-34-252-184-81.eu-west-1.compute.amazonaws.com")
rescue Exception => e
  puts e.inspect
end

lookup
thread = Thread.new do
  loop { lookup ; sleep 3 }
end

sleep 500
```

Interestingly, when converting this to Java, the problem doesn't occur:

```java
import java.net.InetAddress;
import java.util.concurrent.TimeUnit;

public class HostName {
    public static void main(String[] args) throws Exception {
        Thread t = new Thread() {
            public void resolve(String host) {
              try {
                  System.out.println(InetAddress.getByName(host));
              } catch (Exception e) {
                  System.out.println("failed");
                  System.out.println(e.getMessage());
              }
            } 
            public void run() {
                while(true) {
                    try {
                    resolve("ec2-34-252-184-81.eu-west-1.compute.amazonaws.com");
                    TimeUnit.SECONDS.sleep(3);
                    } catch (Exception e) {}
                }
            }
        };
        t.start();
        TimeUnit.SECONDS.sleep(500);
    }
}
```

**Comment by jsvd** [comment] 2017-03-28 15:43
I was able to replicate this issue using just jruby without any libraries, so I opened an issue on the jruby repo: https://github.com/jruby/jruby/issues/4549

**Comment by jsvd** [comment] 2017-11-03 12:01
since I tracked this to jruby I don't see other folks hitting this problem I'm going to close this issue

**Closed by jsvd** 2017-11-03 12:01 UTC
Labels: bug
