### ISSUE TITLE
Logstash 1.5 crashes if it encounters communication problem

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-output-elasticsearch#141] opened 2015-05-18 05:56 UTC
(This issue was originally filed by @spuder at https://github.com/elastic/logstash/issues/3049)

---

This issue is related to #2992 

If logstash 1.5rc2 encounters a problem writing to elasticsearch, it will cause logtsash to crash. 

Full logs are shown here:

http://pastebin.com/tdy8KWay

The interesting lines are:

```
{:timestamp=>"2015-04-17T11:34:24.192000-0600", :message=>"Got error to send bulk of actions to elasticsearch server at swat-elasticsearchpool.ndlab.local : Read timed out", :level=>:error}
{:timestamp=>"2015-04-17T11:34:24.193000-0600", :message=>"Failed to flush outgoing items", :outgoing_count=>5000, :exception=>#<Manticore::Timeout: Read timed out>, :backtrace=>["/opt/logstash/server/vendor/bundle/jruby/1.9/gems/manticore-0.3.5-java/lib/manticore/response.rb:35:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/manticore-0.3.5-java/lib/manticore/response.rb:61:in `call'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/manticore-0.3.5-java/lib/manticore/response.rb:224:in `call_once'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/manticore-0.3.5-java/lib/manticore/response.rb:127:in `code'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/http/manticore.rb:50:in `perform_request'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/base.rb:187:in `perform_request'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/http/manticore.rb:33:in `perform_request'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/client.rb:115:in `perform_request'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.7/lib/elasticsearch/api/actions/bulk.rb:80:in `bulk'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.1.18-java/lib/logstash/outputs/elasticsearch/protocol.rb:82:in `bulk'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.1.18-java/lib/logstash/outputs/elasticsearch.rb:413:in `submit'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.1.18-java/lib/logstash/outputs/elasticsearch.rb:412:in `submit'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.1.18-java/lib/logstash/outputs/elasticsearch.rb:438:in `flush'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.1.18-java/lib/logstash/outputs/elasticsearch.rb:436:in `flush'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1341:in `each'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:193:in `buffer_flush'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:159:in `buffer_receive'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.1.18-java/lib/logstash/outputs/elasticsearch.rb:402:in `receive'", "/opt/logstash/server/lib/logstash/outputs/base.rb:88:in `handle'", "(eval):233:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/server/lib/logstash/pipeline.rb:279:in `output'", "/opt/logstash/server/lib/logstash/pipeline.rb:235:in `outputworker'", "/opt/logstash/server/lib/logstash/pipeline.rb:163:in `start_outputs'"], :level=>:warn}
{:timestamp=>"2015-04-17T14:09:04.890000-0600", :message=>"SIGTERM received. Shutting down the pipeline.", :level=>:warn}
```

Because of issue #2992 the logstash service will fail to be restarted by the upstart watchdog on ubuntu 14.04. 

The config files are:
```
input {
  kafka {
    zk_connect => 'swat-zoo05.example.com:2181/kafka'
    consumer_threads => 3
    topic_id => 'foobar'
  }
}
filter {
  mutate {
    gsub    => [ "[id][batchID]", "\D", "" ]
  }
  mutate {
    convert => [ "[id][batchID]", "integer"]
  }
}
filter {
  mutate {
    gsub    => [ "[id][docID]", "\D", "" ]
  }
  mutate {
    convert => [ "[id][docID]", "integer"]
  }
}
output {
  elasticsearch {
    host => 'swat-elasticsearchpool.example.com'
    cluster => 'foobar-elastic'
    embedded => false
    protocol => 'http'
  }
}
```

**Comment by jhenry82** [comment] 2015-05-18 19:35
Just wanted to point out that this is still occurring in the final 1.5 release. I upgraded to 1.5 GA today and am encountering this frequently.

**Comment by spolk01** [comment] 2015-05-21 11:55
definitely still a problem!!! my log stash stack became unusable, firstly 1.4.2 started to experience out-of-memory issues due to TCP socket memory leaks. I upgraded to 1.5 to fix this and this happens. not a happy puppy :/

**Comment by asatsi** [comment] 2015-05-21 15:09
Yes pretty frequent. It doesn't crash with 1.5.0 GA, but goes into loop with the said error forever.

**Comment by spuder** [comment] 2015-05-21 15:40
Related to: https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/141

**Comment by valentinogagliardi** [comment] 2015-05-23 10:44
Same problem here.

**Comment by bradvido** [comment] 2015-05-26 15:11
Same problem here using 1.5 GA. The elasticsearch output stops sending messages and i see `Got error to send bulk of actions to elasticsearch server at...` in the logs.

**Comment by ameetmk** [comment] 2015-05-31 03:05
Same here too.

**Comment by afzal273** [comment] 2015-06-13 16:59
Why is logstash not reliable and always gives me these errors? Is there any way to fix it?

**Comment by sdklein** [comment] 2015-06-15 16:38
Same issue. 1.5.0.

**Comment by monotek** [comment] 2015-06-15 19:06
+1 on 1.5.0

**Comment by talevy** [comment] 2015-06-15 19:15
@afzal273 @sdklein @monotek we have updated the elasticsearch output plugin to have no timeout.

would you mind trying to upgrade the plugin via `/bin/plugin update logstash-output-elasticsearch` and see if the issue is still occurring? should be version `0.2.8`.

**Comment by afzal273** [comment] 2015-06-15 19:27
I have upgraded it and will let you know how it goes, thanks!

Best,
Afzal.

**Comment by sdklein** [comment] 2015-06-15 20:06
I have as well. Will keep you posted.

**Comment by monotek** [comment] 2015-06-15 20:59
Already did "bin/plugin update" today and got also the 0.2.8 Version before posting here.

**Comment by afzal273** [comment] 2015-06-16 20:31
I'm still seeing logstash freeze and when I try to stop the service it
doesn't stop.

There is nothing in /var/log/logstash/logstash.log, it's just empty. Is
there a way to increase log level in logstash so we know what's going on
and why it's stopping sending logs to elasticsearch even though it's
running? I have logstash running on each server and sending logs to
elasticsearch cluster

service logstash stop
Killing logstash (pid 30562) with SIGTERM
Waiting logstash (pid 30562) to die...
Waiting logstash (pid 30562) to die...
Waiting logstash (pid 30562) to die...
Waiting logstash (pid 30562) to die...
Waiting logstash (pid 30562) to die...
logstash stop failed; still running.

Here's my command line -

ps -ef | grep logstash

logstash 15747     1 99 20:28 pts/2    00:00:05 /usr/bin/java
-XX:+UseParNewGC -XX:+UseConcMarkSweepGC -Djava.awt.headless=true
-XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly
-Djava.io.tmpdir=/var/lib/logstash -Xmx500m -Xss2048k
-Djffi.boot.library.path=/opt/logstash/vendor/jruby/lib/jni
-XX:+UseParNewGC -XX:+UseConcMarkSweepGC -Djava.awt.headless=true
-XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly
-Djava.io.tmpdir=/var/lib/logstash
-Xbootclasspath/a:/opt/logstash/vendor/jruby/lib/jruby.jar -classpath :
-Djruby.home=/opt/logstash/vendor/jruby
-Djruby.lib=/opt/logstash/vendor/jruby/lib -Djruby.script=jruby
-Djruby.shell=/bin/sh org.jruby.Main --1.9
/opt/logstash/lib/bootstrap/environment.rb logstash/runner.rb agent -f
/etc/logstash/conf.d -l /var/log/logstash/logstash.log

Best,
Afzal.

**Comment by deadjoe** [comment] 2015-06-24 06:26
upgrade to 1.5.1 still has the same issue

**Comment by monotek** [comment] 2015-06-24 08:00
same for me

**Comment by afzal273** [comment] 2015-06-24 11:20
Try using fluentd, working well for me so far (td-agent). Definitely not
crashing like logstash.

Best,
Afzal.

**Comment by monotek** [comment] 2015-07-02 09:26
Still not works in 1.5.2:

```
{:timestamp=>"2015-07-02T11:20:52.613000+0200", :message=>"Got error to send bulk of actions: [405] <html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n", :level=>:error}
{:timestamp=>"2015-07-02T11:20:52.614000+0200", :message=>"Failed to flush outgoing items", :outgoing_count=>2, :exception=>#<Elasticsearch::Transport::Transport::Errors::MethodNotAllowed: [405] <html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>
>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/base.rb:135:in `__raise_transport_error'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/base.rb:227:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/http/manticore.rb:54:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/client.rb:119:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.12/lib/elasticsearch/api/actions/bulk.rb:80:in `bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.1-java/lib/logstash/outputs/elasticsearch/protocol.rb:103:in `bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.1-java/lib/logstash/outputs/elasticsearch.rb:505:in `submit'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.1-java/lib/logstash/outputs/elasticsearch.rb:504:in `submit'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.1-java/lib/logstash/outputs/elasticsearch.rb:529:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.1-java/lib/logstash/outputs/elasticsearch.rb:528:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1341:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:112:in `buffer_initialize'", "org/jruby/RubyKernel.java:1511:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:110:in `buffer_initialize'"], :level=>:warn}
{:timestamp=>"2015-07-02T11:20:52.985000+0200", :message=>"Got error to send bulk of actions: [405] <html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n", :level=>:error}
{:timestamp=>"2015-07-02T11:20:52.986000+0200", :message=>"Failed to flush outgoing items", :outgoing_count=>13, :exception=>#<Elasticsearch::Transport::Transport::Errors::MethodNotAllowed: [405] <html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by dev-head** [comment] 2015-07-06 18:49
i am also seeing this happening in 1.5.1

**Comment by fedelemantuano** [comment] 2015-07-08 11:39
I have the same issue with logstash 1.5.2, like @afzal273.
I'm using protocol **transport** in elasticsearch output plugin and I used **node** protocol. 

Besides logstash, I use the script *elasticsearch-py* to index my data and I do not understand why there is indication of those log in /var/log/logstash/logstash.log, maybe the transport connection.
Perhaps in my case that's the problem, I index a lot of mega of data. 
I'll try to do tests with **http** protocol:
https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-protocol
that use only Elasticsearch REST/HTTP interface 

I also increased the HEAP for logstash to 1 Giga but without results.

**Comment by fedelemantuano** [comment] 2015-07-14 07:12
I started in debug logstash and I had this Exception:

```
Exception in thread ">output" java.lang.UnsupportedOperationException
        at java.lang.Thread.stop(Thread.java:869)
        at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
        at java.lang.Thread.run(Thread.java:745)
```

Maybe this problem is caused by huge documents that I index in elasticsearch but not with logstash.

For now I'm using this workaround:

```
#!/bin/bash

if grep Exception /var/log/logstash/logstash.err; then
    kill -9 $(pgrep --group logstash)
    service logstash start
fi
```
kill -9 because I can stop logstash with service logstash stop.

**Comment by fninja** [comment] 2015-07-17 19:10
same behaviour here.
to be honest i must say i tried upgrading logstash and ES together to the latest versions respectively.
plus installing watcher.
the only way i could send logs to elasticsearch was by setting protocol => "http" and by specifying the name of my elasticsearch server.

downgrading both logstash and elasticsearch to what worked previously didn't help.
I might as well go ahead and delete the full installation and start from scratch to see if it might be something awkward in our infrastructure here, but that's what i can share so far.

**Comment by fninja** [comment] 2015-07-17 22:31
downgraded another testing cluster to logstash 1.5.0.rc2 and deleted the datadir of elasticsearch on all ES nodes after uninstalling watcher.
now logs are being pushed again.
My best guess, a wild one, would be it has something to do with watcher.

**Comment by monotek** [comment] 2015-07-22 10:22
i was able to fix my problem by adding "user" and "password" variables to my output.conf.
had this in the "host" variable before .

**Comment by bahaaldine** [comment] 2015-07-28 20:58
fixed on my side by adding protocol => "http"

**Comment by suyograo** [comment] 2015-08-03 21:21
So there's a lot of different issues which have been rolled into this one and is very difficult to follow. Can you please open separate issues with debug info so we can fix this properly? Thanks much!

**Comment by suyograo** [comment] 2015-08-03 21:25
@fninja did you have Watcher installed on your ES cluster?

**Comment by suyograo** [comment] 2015-08-03 21:26
@fedelemantuano can you please provide a sample doc if possible? are you still hitting this issue? If so  can you open a new issue with the details? thanks!

**Comment by andrewvc** [comment] 2015-08-03 22:01
@afzal273 if you have a chance, could you run logstash in the foreground with '-f' and show us the output from that? It would be a big help to us in debugging this tricky issue.

**Comment by andrewvc** [comment] 2015-08-03 22:06
@suyograo the general common denominator here is people just not being able to connect to ES for one reason or the other. I propose we always run a healthcheck on plugin register and spit out a friendlier (but fatal) error to separate issues on individual requests from transient connection issues.

Additionally, I recommend we not make these connection issues fatal errors. If someone temporarily loses ES connectivity that should not bork logstash. 

@talevy @jordansissel your thoughts?

**Comment by fninja** [comment] 2015-08-06 11:47
@suyograo Hi, yes i had watcher installed, hoping that i could evaluate it for possible later production use.

**Comment by suyograo** [comment] 2015-08-06 18:52
@fninja ok, re:watcher and LS, have you seen this? https://www.elastic.co/guide/en/watcher/current/troubleshooting.html#_logstash_can_8217_t_connect_to_elasticsearch_after_installing_watcher

**Comment by suyograo** [comment] 2015-08-06 18:56
I am going to close this issue. 1.5.3 fixed the read timeout issue (https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/103) which was the original reported error by @spuder.

There's a lot of responses here and many issues are not related to the original issue. It is really hard to debug anything on this thread because of all the responses. Please reopen new issues with information when you encounter communication problems so we can properly debug and fix them. Don't worry about duplicates, we'll sort them out :)

**Closed by suyograo** 2015-08-06 18:56 UTC

**Comment by fninja** [comment] 2015-08-13 12:21
@suyograo awesome! thanks, i didn't know of that one.

**Comment by claflico** [comment] 2015-10-28 15:22
Just in case anyone else ends up here as the result of a Google search of the error message in the first post and is using Logstash 1.5.4, save yourself several hours of troubleshooting and see this link: 
https://github.com/elastic/logstash/issues/3776
