### ISSUE TITLE
Bulk request on a 404 index doesn't log anything

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-output-elasticsearch#584] opened 2017-04-10 17:42 UTC
originally reported by @robin13 

if you disable auto creation of index "test" on elasticsearch in the `elasticsearch.yml` like this:

```
action.auto_create_index: .security,.monitoring*,.watches,.triggered_watches,.watcher-history*
```

And you try to send events to that specific index, logtash will just drop events on the floor without reporting anything in the logs. If we look at the raw response from ES:

```
{  
   "error":{  
      "root_cause":[  
         {  
            "type":"index_not_found_exception",
            "reason":"no such index and [action.auto_create_index] ([.security,.monitoring*,.watches,.triggered_watches,.watcher-history*]) doesn't match",
            "index_uuid":"_na_",
            "index":"test"
         }
      ],
      "type":"index_not_found_exception",
      "reason":"no such index and [action.auto_create_index] ([.security,.monitoring*,.watches,.triggered_watches,.watcher-history*]) doesn't match",
      "index_uuid":"_na_",
      "index":"test"
   },
   "status":404
}```
```

The issue is because we expect in the code to receive an "errors" key the plural form and not the singular. Because we check for error for each document. See https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/http_client.rb#L128-L133

Because of this the output think everything went fine when sending the request to the server but in reality we just silently drop the event.

**Comment by jordansissel** [comment] 2017-04-10 17:49
https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/583 was recently merged that changed a bit how we handle failures.

Part of this change was to consider 404 as a permanent delivery failure. WHen DLQ is enabled, this means 404'd documents will be put into the DLQ. When DLQ is disabled (default?), this means we will log the failure and drop the event.

I think #583 may have solved this?

**Comment by ph** [comment] 2017-04-10 17:57
This is what I thought too, before I look more at the code, but It wont solve this error.
We will suffer from the same bug because the `#safe_bulk` will return this 

```
=> {"errors"=>true, "items"=>[]}
```
Making the loop actually a NOOP, our error handling depends on "items" of a bulk request and we don't take into consideration that a whole bulk request can fail. See https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/583/files#diff-80f5e58dec942267dcee4b6f182bdfcfR125

**Comment by jordansissel** [comment] 2017-04-10 18:01
Hmm... safe_bulk itself should handle actual request failures (not per document failures).

Further, how would we get a 404 on an entire /_bulk? 

Upon further inspection a 404 response code is [not considered bad](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/9f6fbcddce7a7127c502b5c48ad3d7c25b65a649/lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb#L76-L81) by our client.

I wonder if a '404 on /_bulk' is even possible? Can you reproduce this?

**Comment by ph** [comment] 2017-04-10 18:56
@jordansissel I can reproduce it with the description in this issue. Adding this to your `elasticsearch.yml`, will make `_bulk` return a 404.

```
action.auto_create_index: .security,.monitoring*,.watches,.triggered_watches,.watcher-history*
```

**Comment by robin13** [comment] 2017-04-10 19:10
Yes - 404 both in the http response code and the 'status' field in the
elasticsearch response.

**Comment by jordansissel** [comment] 2017-04-10 19:11
@ph On Logstash 5.3.0 and Elasticsearch 5.1.2, I see this:

```
[2017-04-09T03:07:45,518][WARN ][logstash.outputs.elasticsearch] Failed action. {:status=>404, :action=>["index", {:_id=>nil, :_index=>"logstash-2017.04.09", :_type=>"stdin", :_routing=>nil}, 2017-04-09T10:07:45.472Z localhost.localdomain hello], :response=>{"index"=>{"_index"=>"logstash-2017.04.09", "_type"=>"stdin", "_id"=>nil, "status"=>404, "error"=>{"type"=>"index_not_found_exception", "reason"=>"no such index", "resource.type"=>"index_expression", "resource.id"=>"logstash-2017.04.09", "index_uuid"=>"_na_", "index"=>"logstash-2017.04.09"}}}}
```

The response is a 404 on the individual document, not the whole /_bulk request.

When I sniff the http traffic, I see HTTP 200 in the HTTP response code.

**Comment by ph** [comment] 2017-04-10 19:13
@jordan did you disable `auto_create_index` for logstash*?

**Comment by jordansissel** [comment] 2017-04-10 19:15
Yes:

```
action.auto_create_index: .security,.monitoring*,.watches,.triggered_watches,.watcher-history*
```

**Comment by ph** [comment] 2017-04-10 19:17
The only difference is I am on ES 3.0.

**Comment by jordansissel** [comment] 2017-04-10 19:24
```
T 127.0.0.1:53714 -> 127.0.0.1:9200 [AP]
  POST /_bulk HTTP/1.1..Connection: Keep-Alive..Content-Type: application/jso
  n..Content-Length: 209..Host: 127.0.0.1:9200..User-Agent: Manticore 0.6.1..
  Accept-Encoding: gzip,deflate....{"index":{"_id":null,"_index":"logstash-20
  17.04.09","_type":"stdin","_routing":null}}.{"@timestamp":"2017-04-09T10:34
  :25.253Z","@version":"1","host":"localhost.localdomain","message":"testing"
  ,"type":"stdin"}.
#
T 127.0.0.1:9200 -> 127.0.0.1:53714 [AP]
  HTTP/1.1 200 OK..content-type: application/json; charset=UTF-8..content-enc
  oding: gzip..transfer-encoding: chunked....bc............|.M..0..."..%JA.UD
  BhF....L.Rrw.6.\.n~.|...L..).@.....#6`....,`......V0.=....(..Vt.8C.._......
  .[...ql.Hs..Nt....~.*G.n..Q8.8.....C.$8.....-BY...........s[%%....w..D9.2..
  .).kz.......a....O...4.....0....
```

**Comment by jordansissel** [comment] 2017-04-10 19:25
Trying with curl:

```
% cat /tmp/x
{"index":{"_id":null,"_index":"logstash-2017.04.09","_type":"stdin","_routing":null}}
{"@timestamp":"2017-04-09T10:34:25.253Z","@version":"1","host":"localhost.localdomain","message":"testing","type":"stdin"}
```

```
% curl -D- --data-binary @/tmp/x localhost:9200/_bulk?pretty
HTTP/1.1 200 OK
content-type: application/json; charset=UTF-8
content-length: 496

{
  "took" : 0,
  "errors" : true,
  "items" : [
    {
      "index" : {
        "_index" : "logstash-2017.04.09",
        "_type" : "stdin",
        "_id" : null,
        "status" : 404,
        "error" : {
          "type" : "index_not_found_exception",
          "reason" : "no such index",
          "resource.type" : "index_expression",
          "resource.id" : "logstash-2017.04.09",
          "index_uuid" : "_na_",
          "index" : "logstash-2017.04.09"
        }
      }
    }
  ]
}
```

**Comment by ph** [comment] 2017-04-10 19:27
```
zsh: no matches found: http://localhost:9200/_bulk?pretty
✘ ⚙ph@sashimi~/es/logstash  fix/refactor-config-multiple-pipeline ± curl -D- --data-binary @/tmp/x "http://localhost:9200/_bulk?pretty"                                                                                                                                                                                 ⏎
HTTP/1.1 404 Not Found
Warning: 299 Elasticsearch-5.3.0-3adb13b "Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header." "Mon, 10 Apr 2017 19:26:48 GMT"
content-type: application/json; charset=UTF-8
content-length: 610

{
  "error" : {
    "root_cause" : [
      {
        "type" : "index_not_found_exception",
        "reason" : "no such index and [action.auto_create_index] ([.security,.monitoring*,.watches,.triggered_watches,.watcher-history*]) doesn't match",
        "index_uuid" : "_na_",
        "index" : "logstash-2017.04.09"
      }
    ],
    "type" : "index_not_found_exception",
    "reason" : "no such index and [action.auto_create_index] ([.security,.monitoring*,.watches,.triggered_watches,.watcher-history*]) doesn't match",
    "index_uuid" : "_na_",
    "index" : "logstash-2017.04.09"
  },
  "status" : 404
}
```

**Comment by ph** [comment] 2017-04-10 19:29
@jordansissel I've used the same document as you, look like the behavior changed between 5.1.x -> 5.3.X

**Comment by jordansissel** [comment] 2017-04-10 19:30
Hmm... confirmed on 5.3.0:

```
% curl -H "Content-Type: application/json" -D- --data-binary @/tmp/x localhost:9200/_bulk?pretty
HTTP/1.1 404 Not Found
content-type: application/json; charset=UTF-8
content-length: 610
...
```

**Comment by ph** [comment] 2017-04-10 19:33
Seem related to this change:  https://github.com/elastic/elasticsearch/pull/22488

From https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-5.3.0.html

**Comment by jordansissel** [comment] 2017-04-10 19:38
Ok here's what I know so far:

* Elasticsearch 5.1.2 responds with HTTP 200 
* Elasticseiarch 5.2.1 responds with HTTP 200
* Elasticsearch 5.3.0 responds with HTTP 404

I do not expect HTTP 404. I see no obvious changes in the ES 5.3 release notes to indicate this new change (though I only skimmed it)

**Comment by jordansissel** [comment] 2017-04-10 19:43
Ok following up here:

* @ph and I think this is a bug in Elasticsearch 5.3.0. @ph will file an issue on ES.
* We do not expect a 404 response code for the request.

In cases of unexpected response codes, I am not quite sure what we should do:

1) Should we shutdown Logstash because an unexpected response is an indication that the ES output is not actually talking to a valid Elasticsearch server? (bugs notwithstanding)
2) or, should we log that the entire request has unclear delivery result (and soon, put all these events in the DLQ) ?

**Comment by jordansissel** [comment] 2017-04-10 19:44
Interestingly, this problem (a 404 in the HTTP response) only occurs for me if the _bulk has only a single entry. If there are two entries, the response code is correctly a 200 (and the response body indicates that both index actions failed with status 404)

**Comment by ph** [comment] 2017-04-10 19:45
@jordansissel Also if you target two index, one in the whitelisting list and not the other, you will get a unique response from the server.

**Comment by ph** [comment] 2017-04-10 19:56
> or, should we log that the entire request has unclear delivery result (and soon, put all these events in the DLQ) ?

I think that what we should do, we need to do a bit more asserts on the returned data, to at least have a items fields.

**Comment by jordansissel** [comment] 2017-04-10 19:56
I think the ES bug tickled an odd integration problem in Logstash -- https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb#L76-L81

We consider a 404 response code to be OK.

I wonder if we should change response code handling to be explicit instead of using exceptions?

**Comment by ph** [comment] 2017-04-11 00:55
I've put some more thoughts, I think we should do the following, we need to change the response handling to be more explicite of the http code.

The problem is the template and the bulk request goes into the same logic path and they shouldn't because in these 2 scenarios a 404 mean completely 2 different things.

I also think HTTP CODE >  status code in json, since the http code operate on a server level.

**The health check path probably use the same code path too, I haven't looked at it**

**Comment by ph** [comment] 2017-04-21 14:13
This was bring up in the meeting and we should change the behavior in the context of a bulk request, we should check the *HTTP response code* and log it. Our current code we only care about the error code in the actual json response.

**Comment by jsvd** [comment] 2017-11-06 11:05
Current logstash 5.6.3 presents a proper error message:

```
[2017-11-06T11:04:29,659][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>404, :action=>["index", {:_id=>nil, :_index=>"a", :_type=>"logs", :_routing=>nil}, 2017-11-06T11:04:28.127Z Joaos-MacBook-Pro-5.local a], :response=>{"index"=>{"_index"=>"a", "_type"=>"logs", "_id"=>nil, "status"=>404, "error"=>{"type"=>"index_not_found_exception", "reason"=>"no such index and [action.auto_create_index] ([.security,.monitoring*,.watches,.triggered_watches,.watcher-history*]) doesn't match", "index_uuid"=>"_na_", "index"=>"a"}}}}
[2017-11-06T11:04:29,660][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>404, :action=>["index", {:_id=>nil, :_index=>"b", :_type=>"logs", :_routing=>nil}, 2017-11-06T11:04:28.391Z Joaos-MacBook-Pro-5.local b], :response=>{"index"=>{"_index"=>"b", "_type"=>"logs", "_id"=>nil, "status"=>404, "error"=>{"type"=>"index_not_found_exception", "reason"=>"no such index and [action.auto_create_index] ([.security,.monitoring*,.watches,.triggered_watches,.watcher-history*]) doesn't match", "index_uuid"=>"_na_", "index"=>"b"}}}}
```

I don't see any other scenario that justifies keeping this open, so I'm closing the issue.

**Closed by jsvd** 2017-11-06 11:05 UTC
Labels: bug
