### ISSUE TITLE
update action failing

### ISSUE THREAD

**Issue by nsiitk** [logstash-plugins/logstash-output-elasticsearch#273] opened 2015-10-16 05:49 UTC
I was trying logstash2.0 beta2 with elasticsearch 2.0.0.rc1 with config

 elasticsearch { hosts => ['localhost'] 
        action => "update"
        document_id => "%{msgid}"
        doc_as_upsert => true
        } 
and output is failing with expected START_OBJECT or END_OBJECT but found [VALUE_STRING]. 
 There was no issue with logstash1.5.4 and elasticsearch1.7.2
i haven't tested delete but similar issue seams to be like #195 

Attempted to send a bulk request to Elasticsearch configured at '["http://localhost:9200/"]', but an error occurred and it failed! Are you sure you can reach elasticsearch from this machine using the configuration provided? {:client_config=>{:hosts=>["http://localhost:9200/"], :ssl=>nil, :transport_options=>{:socket_timeout=>0, :request_timeout=>0, :proxy=>nil, :ssl=>{}}, :transport_class=>Elasticsearch::Transport::Transport::HTTP::Manticore, :logger=>nil, :tracer=>nil, :reload_connections=>false, :retry_on_failure=>false, :reload_on_failure=>false, :randomize_hosts=>false}, :error_message=>"[400] {\"error\":{\"root_cause\":[{\"type\":\"illegal_argument_exception\",\"reason\":\"Malformed action/metadata line [15], expected START_OBJECT or END_OBJECT but found [VALUE_STRING]\"}],\"type\":\"illegal_argument_exception\",\"reason\":\"Malformed action/metadata line [15], expected START_OBJECT or END_OBJECT but found [VALUE_STRING]\"},\"status\":400}", :error_class=>"Elasticsearch::Transport::Transport::Errors::BadRequest", :backtrace=>["/Users/nitinsingh/dev/elastic/logstash-2.0.0-beta2/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/base.rb:136:in `__raise_transport_error'", "/Users/nitinsingh/dev/elastic/logstash-2.0.0-beta2/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/base.rb:228:in`perform_request'", "/Users/nitinsingh/dev/elastic/logstash-2.0.0-beta2/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/http/manticore.rb:54:in `perform_request'", "/Users/nitinsingh/dev/elastic/logstash-2.0.0-beta2/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/client.rb:119:in`perform_request'", "/Users/nitinsingh/dev/elastic/logstash-2.0.0-beta2/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/actions/bulk.rb:87:in `bulk'", "/Users/nitinsingh/dev/elastic/logstash-2.0.0-beta2/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:56:in`bulk'", "/Users/nitinsingh/dev/elastic/logstash-2.0.0-beta2/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.1-java/lib/logstash/outputs/elasticsearch.rb:351:in `submit'", "org/jruby/ext/thread/Mutex.java:149:in`synchronize'", "/Users/nitinsingh/dev/elastic/logstash-2.0.0-beta2/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.1-java/lib/logstash/outputs/elasticsearch.rb:348:in `submit'", "/Users/nitinsingh/dev/elastic/logstash-2.0.0-beta2/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.1-java/lib/logstash/outputs/elasticsearch.rb:380:in`flush'", "/Users/nitinsingh/dev/elastic/logstash-2.0.0-beta2/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1342:in`each'", "/Users/nitinsingh/dev/elastic/logstash-2.0.0-beta2/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:216:in `buffer_flush'", "/Users/nitinsingh/dev/elastic/logstash-2.0.0-beta2/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:193:in`buffer_flush'", "/Users/nitinsingh/dev/elastic/logstash-2.0.0-beta2/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:112:in `buffer_initialize'", "org/jruby/RubyKernel.java:1479:in`loop'", "/Users/nitinsingh/dev/elastic/logstash-2.0.0-beta2/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:110:in `buffer_initialize'"], :level=>:error}

**Comment by nsiitk** [comment] 2015-10-16 10:45
request fails when message object contains nested object otherwise its ok.

@store={"data"=>{"message_status"=>"MESSAGE_SENT_TO_DEVICE", "device_registration_id"=>"acl_device", "message_sent_timestamp"=>"1444990531680", "original_message_id"=>"hdfc-1444989168589-90e99019"}, "category"=>"com.itsoninc.client", "@version"=>"1", "@timestamp"=>"2015-10-16T10:15:33.099Z", "tags"=>["receipts"], "delivertimestamp"=>"2015-10-16T10:15:31.680Z", "dr_message_id"=>"dr2:hdfc-1444989168589-90e99019", "dr_message_type"=>"receipt", "gcm_host"=>"gcm.googleapis.com", "device_id"=>"acl_device", "msgid"=>"hdfc-1444989168589-90e99019"}



log4j, [2015-10-16T15:46:39.359] DEBUG: org.apache.http.wire: http-outgoing-0 >> "{"update":{"_id":"hdfc-1444989417017-74874a7a","_index":"logstash-2015.10.16","_type":"logs","_routing":null}}[\n]"
log4j, [2015-10-16T15:46:39.359] DEBUG: org.apache.http.wire: http-outgoing-0 >> "{"doc":{"category":"com.itsoninc.client","@version":"1","@timestamp":"2015-10-16T10:15:33.208Z","tags":["receipts"],"delivertimestamp":"2015-10-16T10:15:31.680Z","dr_message_id":"dr2:hdfc-1444989417017-74874a7a","dr_message_type":"receipt","gcm_host":"gcm.googleapis.com","device_id":"acl_device","msgid":"hdfc-1444989417017-74874a7a"}}[\n]"
log4j, [2015-10-16T15:46:39.359] DEBUG: org.apache.http.wire: http-outgoing-0 >> "{"message_status":"MESSAGE_SENT_TO_DEVICE","device_registration_id":"acl_device","message_sent_timestamp":"1444990531680","original_message_id":"hdfc-1444989417017-74874a7a"}[\n]"

**Comment by nsiitk** [comment] 2015-10-16 11:38
issue seems to be with field name data as renaming it has solved the issue.

**Comment by suyograo** [comment] 2015-10-16 15:38
@nsiitk from your original data, i can't see which is nested object.. can you paste that snippet here?

**Comment by nsiitk** [comment] 2015-10-16 16:16
from the kafka logs the input data format is

{"data":{"message_status":"MESSAGE_SENT_TO_DEVICE","device_registration_id":"abc-33","message_sent_timestamp":"1444281905838","original_message_id":"m-33"},"message_type":"receipt","from":"gcm.googleapis.com","message_id":"dr2:m-33","category":"com.itsoninc.client"}

**Comment by german23** [comment] 2015-11-02 09:40
I also encoutered this bug with the "geoip" filter in logstash, that basically creates a nested field ( geoip.ip, geoip.country:name, geoip.timezone , etc... ) 

After removing this filter, everything worked fine again (logstash 2.0.0)

**Comment by kevross33** [comment] 2015-11-09 11:32
Hi,

I am having this issue too. Updated to logstash 2.0, elasticsearch 2.0 and now unless I disable geoip filters logstash will stop sending logs after a few minutes of running. I am wondering if it is because elasticsearch doesn't like dots in fieldnames anymore (had this issue with bro) but it is putting in fields like geoip.country:name. 

I am not getting any errors out aside from messages about bulk sending fails and only when geoip is disabled did this stop happening although there was no log I can see that indicates anything pointing to geoip plugin.

**Comment by kevross33** [comment] 2015-11-09 11:33
oh sorry I though this was very similar to the issue I was having but I misread what was going on.

**Comment by AdeMiller** [comment] 2015-11-12 16:36
Has there been any progress on this. It is basically preventing me from using Logstash as a large number of my messages get dropped by the bulk uploader in 2.0.0-1. The last version of LS I was able to use successfully was 1.4

```
{:timestamp=>"2015-11-12T15:55:45.864000+0000", :message=>"Attempted to send a bulk request to Elasticsearch configured at '[\"http://elasticsearchda-qa9-01.t3qa.dom:9200/\", \"http://elasticsearchda-qa9-02.t3qa.dom:9200/\", \"http://elasticsearchda-qa9-03.t3qa.dom:9200/\"]', but an error occurred and it failed! Are you sure you can reach elasticsearch from this machine using the configuration provided?", :client_config=>{:hosts=>["http://elasticsearchda-qa9-01.t3qa.dom:9200/", "http://elasticsearchda-qa9-02.t3qa.dom:9200/", "http://elasticsearchda-qa9-03.t3qa.dom:9200/"], :ssl=>nil, :transport_options=>{:socket_timeout=>0, :request_timeout=>0, :proxy=>nil, :ssl=>{}}, :transport_class=>Elasticsearch::Transport::Transport::HTTP::Manticore, :headers=>{"Authorization"=>"Basic bG9nc3Rhc2hfdXNlcjpQYXNzd29yZDE="}, :logger=>nil, :tracer=>nil, :reload_connections=>false, :retry_on_failure=>false, :reload_on_failure=>false, :randomize_hosts=>false}, :error_message=>"[500] {\"error\":\"IllegalArgumentException[Malformed action/metadata line [3], expected START_OBJECT or END_OBJECT but found [VALUE_STRING]]\",\"status\":500}", :error_class=>"Elasticsearch::Transport::Transport::Errors::InternalServerError", :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/base.rb:136:in `__raise_transport_error'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/base.rb:228:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/http/manticore.rb:54:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/client.rb:119:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/actions/bulk.rb:87:in `bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch/http_client.rb:56:in `bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch.rb:353:in `submit'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch.rb:350:in `submit'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch.rb:382:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1342:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:193:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:159:in `buffer_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch.rb:343:in `receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/outputs/base.rb:80:in `handle'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/outputs/base.rb:71:in `worker_setup'"], :level=>:error}
```

**Comment by AdeMiller** [comment] 2015-11-12 18:23
I just reverted to Logstash 1.5.5-1 and am seeing a similar error

```
{:timestamp=>"2015-11-12T18:22:23.871000+0000", :message=>"Got error to send bulk of actions: can't convert Symbol into String", :level=>:error}
{:timestamp=>"2015-11-12T18:22:23.871000+0000", :message=>"Failed to flush outgoing items", :outgoing_count=>500, :exception=>"TypeError", :backtrace=>["org/jruby/RubyString.java:6326:in `delete!'", "org/jruby/RubyString.java:6305:in `delete'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/utils.rb:86:in `__bulkify'", "org/jruby/RubyArray.java:1613:in `each'", "org/jruby/RubyEnumerable.java:852:in `inject'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/utils.rb:82:in `__bulkify'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/actions/bulk.rb:82:in `bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch/protocol.rb:104:in `bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch.rb:542:in `submit'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch.rb:541:in `submit'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch.rb:566:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch.rb:565:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1342:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:193:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:159:in `buffer_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch.rb:531:in `receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.5-java/lib/logstash/outputs/base.rb:88:in `handle'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.5-java/lib/logstash/outputs/base.rb:79:in `worker_setup'"], :level=>:warn}
```

**Comment by AdeMiller** [comment] 2015-11-12 20:16
Seems like it's something to do with nested fields and their names...

Succeeds: 
``` 
{"json_message":{"source":"ADE_TEST_2","foo":{"nats_message":""}} } 
```

FAILs: 
``` 
{"json_message":{"source":"ADE_TEST_2","data":{"nats_message":""}} } 
```

Error: 
``` 
/logstash/pipeline.rb:244:in `outputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.5-java/lib/logstash/pipeline.rb:166:in `start_outputs'"], :level=>:warn} 
{:timestamp=>"2015-11-12T20:13:25.669000+0000", :message=>"Got error to send bulk of actions: [500] {\"error\":\"IllegalArgumentException[Malformed action/metadata line [3], expected START_OBJECT or END_OBJECT but found [VALUE_STRING]]\",\"status\":500}", :level=>:error} 
{:timestamp=>"2015-11-12T20:13:25.669000+0000", :message=>"Failed to flush outgoing items", :outgoing_count=>1, :exception=>"Elasticsearch::Transport::Transport::Errors::InternalServerError", :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/base.rb:136:in `__raise_transport_error'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/base.rb:228:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/http/manticore.rb:54:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/client.rb:119:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/actions/bulk.rb:87:in `bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch/protocol.rb:104:in `bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch.rb:542:in `submit'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch.rb:566:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1342:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:159:in `buffer_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch.rb:531:in `receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.5-java/lib/logstash/outputs/base.rb:88:in `handle'", "(eval):421:in `output_func'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.5-java/lib/logstash/pipeline.rb:244:in `outputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.5-java/lib/logstash/pipeline.rb:166:in `start_outputs'"], :level=>:warn}

**Comment by kevross33** [comment] 2015-11-13 08:56
Hi,

I have a similar issue to this too (get the same error message). I stopped
getting it when I disabled any geoip filters (which I use for security data
enrichment so I really want to locate the cause in my setup of this).
Anyway what would happen when I have geoip active is that it will run for a
few minutes and then eventually stop logging but not crash (basically it
ends hung/problem state and I have to explicitly kill the daemon).

I was hoping it would just stop working immediately to identify what it
isn't liking but I imagine it is reading something in it does not like as
it works fine as I said for a few mins adding in geoip data and then just
stops.

**Comment by phildonaldson** [comment] 2015-11-13 12:55
I'm currently doing some test development on ELK and we have the exact same issue after our recent upgrade to logstash 2.0 / elasticsearch 2.0.

Removing the geoip configuration allows me to import ~137k lines from a static file, but with the geoip configuration in place it only imports ~11k records (presumable those log lines that do not contain IP data).

Geoip is the only configuration I have that contains nested fields.

**Comment by kevross33** [comment] 2015-11-18 15:02
Hi,

Anyone know how to troubleshoot this or (hopefully) fix it? Thanks.

**Comment by AdeMiller** [comment] 2015-11-19 19:53
I would try renaming some of the geoip fields and see if that fixes it. For my 'data' field name issue this resolves the problem for LS 2.0.0-1 with ES 1.7.3

```
        mutate { rename => { "[json_message][data]" => "[json_message][json_data]" } }
```
However if you have to rename fields within the `geoip` it will no longer be valid from the geoip perspective.

**Comment by kevross33** [comment] 2015-11-25 11:05
Hi,

It seems in my case this may have been caused by memory allocated to the
logstash heap which has been increased in version 2.1. I will keep
monitoring it and if it happens again I will increase it but it seems more
stable now although I did not realise this had been changed.

Kind Regards,
Kevin Ross

**Comment by andrewvc** [comment] 2016-12-20 21:15
Apologies for the extreme delay in answering this thread. Are you all still experiencing this? Similar bugs have been fixed and this output has been massively refactored since these issues were reported.

**Comment by jeremiahhoyle** [comment] 2017-06-05 20:06
I am new to this but I am seeing this same issue. I can't see that this is caused by nested data.

**Comment by guyboertje** [comment] 2017-11-07 12:48
@jeremiahhoyle 
Thanks for your response, sorry about the delay.
If you are still having a similar problem as listed here with the latest versions of LS and the elasticsearch output will you please reply with a **lot** of detail explaining the fault you see.

Otherwise, I'm closing this issue in about two weeks from now.

**Closed** 2017-11-21 10:55 UTC
Labels: bug
