### ISSUE TITLE
Unexpected error when plugin tries to resurrect connection to Elasticsearch

### ISSUE THREAD

**Issue by fbaligand** [logstash-plugins/logstash-output-elasticsearch#750] opened 2018-03-19 10:30 UTC
I had a case where Logstash loose connection to Elasticsearch, then tries to resurrect it, and raises an unexpected error, which brings to Logstash brutal shutdown.
So it is a critical bug.

Here's the logs : 

```
[2018-03-15T09:46:37,812][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://logstash:xxxxxx@localhost:10400/, :path=>"/"}
[2018-03-15T09:46:37,815][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://logstash:xxxxxx@localhost:10400/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError, :error=>"Got response code '403' contacting Elasticsearch at URL 'http://localhost:10400/'"}
[2018-03-15T09:46:41,692][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<NoMethodError: undefined method `<' for nil:NilClass>, :backtrace=>["/usr/product/logstash/logstash-6.1.3/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.0.2-java/lib/logstash/outputs/elasticsearch/common.rb:213:in `get_event_type'", "/usr/product/logstash/logstash-6.1.3/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.0.2-java/lib/logstash/outputs/elasticsearch/common.rb:165:in `event_action_params'", "/usr/product/logstash/logstash-6.1.3/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.0.2-java/lib/logstash/outputs/elasticsearch/common.rb:39:in `event_action_tuple'", "/usr/product/logstash/logstash-6.1.3/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.0.2-java/lib/logstash/outputs/elasticsearch/common.rb:34:in `block in multi_receive'", "org/jruby/RubyArray.java:2486:in `map'", "/usr/product/logstash/logstash-6.1.3/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.0.2-java/lib/logstash/outputs/elasticsearch/common.rb:34:in `multi_receive'", "/usr/product/logstash/logstash-6.1.3/logstash-core/lib/logstash/output_delegator_strategies/shared.rb:13:in `multi_receive'", "/usr/product/logstash/logstash-6.1.3/logstash-core/lib/logstash/output_delegator.rb:50:in `multi_receive'", "/usr/product/logstash/logstash-6.1.3/logstash-core/lib/logstash/pipeline.rb:487:in `block in output_batch'", "org/jruby/RubyHash.java:1343:in `each'", "/usr/product/logstash/logstash-6.1.3/logstash-core/lib/logstash/pipeline.rb:486:in `output_batch'", "/usr/product/logstash/logstash-6.1.3/logstash-core/lib/logstash/pipeline.rb:438:in `worker_loop'", "/usr/product/logstash/logstash-6.1.3/logstash-core/lib/logstash/pipeline.rb:393:in `block in start_workers'"]}
```

**Comment by jsvd** [comment] 2018-03-19 10:53
this seems to be a duplicate of https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/715

as we understand it, it's an issue when logstash has yet to figure out which version of elasticsearch it is connecting to. can you confirm this happened after things were already working normally and disconnected afterwards?

**Comment by fbaligand** [comment] 2018-03-19 14:19
I had the problem at Logstash startup after numerous tries to connect to Elasticsearch.

**Comment by jsvd** [comment] 2018-03-19 15:25
which version of elasticsearch was this?
the exception will manifest itself as a consequence of not being able to connect the cluster for the normal reasons (firewall, wrong ip, credentials, etc), but shouldn't be the reason for it to not connect.

**Comment by fbaligand** [comment] 2018-03-19 15:28
Logstash : 6.1.3
Elasticsearch : 6.1.3
logstash-output-elasticsearch : 9.0.2-java

**Comment by fbaligand** [comment] 2018-03-19 15:30
The fact that Logstash doesn't arrive to connect to Elasticsearch is the cause.
In my case, the user/password sent to elasticsearch was wrong.
But the problem is that it brings to a NullPointerException and so, a Logstash brutal shutdown.

**Closed** 2018-05-15 15:57 UTC
Labels: bug
