### ISSUE TITLE
Working with LS ES output and allow_explicit_index = false

### ISSUE THREAD

**Issue by teebu** [logstash-plugins/logstash-output-elasticsearch#374] opened 2016-02-26 23:16 UTC
I've been using LS1.5 with 'node' protocol before without problems. I'm testing LS2.2, and I'm running into a problem. (Reason for upgrading is to use scripting)

```
 [500] {"error":"IllegalArgumentException[explicit index in bulk is not allowed]","status":500}
```

Related discussions:
https://github.com/elastic/elasticsearch/issues/7256
https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/194

my basic test:

```
bin/logstash -e '
input { 
    stdin { } 
} 
output { 
    elasticsearch {
        hosts=>["localhost"]
        index => "testing"
    }
  stdout {codec => rubydebug } 
}'
```

How do I go about solving this, without setting allow_explicit_index: true.

```
rest.action.multi.allow_explicit_index: true
```

**Comment by einyx** [comment] 2016-03-10 15:55
:+1: please fix

**Comment by mohantnr** [comment] 2016-09-23 06:02
how to fix the issue without setting rest.action.multi.allow_explicit_index to true.?

**Comment by jordansissel** [comment] 2016-09-23 06:58
@mohantnr This is the first I've learned about the `rest.action.multi.allow_explicit_index` setting, and I have no idea what its purpose is, so I don't have much in the way of advising you on what to do.

**Comment by jordansissel** [comment] 2016-09-23 07:00
I had a glance at https://www.elastic.co/guide/en/elasticsearch/reference/current/url-access-control.html, and I think the best answer I can provide right now is to use Shield for access control instead of using URL-based filtering in some kind of http proxy.

As for making the elasticsearch output work with this scenario, I am open to patches that make it work.

**Comment by mohantnr** [comment] 2016-09-23 08:01
Thank you for the reply. When can we expect the patch for the logstash to address this issue.

**Comment by joshuaspence** [comment] 2016-10-06 20:47
I think that this is a duplicate of #194?

**Comment by jsvd** [comment] 2018-05-17 08:35
closing as duplicate of #194

**Closed by jsvd** 2018-05-17 08:35 UTC
