### ISSUE TITLE
Bulk Request Fails in Logstash

### ISSUE THREAD

**Issue by tamiliniyaan** [logstash-plugins/logstash-output-elasticsearch#612] opened 2017-06-16 05:32 UTC
I am getting the following message while start a logstash .

Version ES and Logstash - 5.1.1 
OS : CentOS

output plugin as ,
elasticsearch {
                hosts =>["10.4.1.70:9299"]
                index => "%{[@metadata][INDEX_NAME]}"
                document_type => "logs"
        }

[2017-06-16T05:31:44,494][ERROR][logstash.outputs.elasticsearch] Got a bad response code from server, but this code is not considered retryable. Request will be dropped {:code=>400, :response_body=>"No handler found for uri [/_template/logstash/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk] and method [POST]"}

It will try for  the logstash template.

**Comment by nanjj** [comment] 2017-07-06 17:12
similar problem here:
```
[ERROR][logstash.outputs.elasticsearch] Got a bad response code from server, but this code is not considered retryable. Request will be dropped {:code=>400, :response_body=>"No handler found for uri [/_bulk/_bulk/_bulk/_bulk] and method [POST]
```

**Comment by amitavmohanty01** [comment] 2017-10-03 23:48
I can confirm this is happening in 5.6.2 as well.

I am pushing data from Filebeat. Once the error starts, logstash can't shut down either because there are events that it needs to post.

`[2017-10-04T05:13:40,572][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>31, "stalling_thread_info"=>{["LogStash::Filters::GeoIP", {"source"=>"clientip", "id"=>"48cf85ce3f5dc3026170d3268abe03cf9acbe9d4-3"}]=>[{"thread_id"=>28, "name"=>"[main]>worker4", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.23/lib/stud/interval.rb:89:in 'sleep'"}]}}
[2017-10-04T05:13:45,572][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>31, "stalling_thread_info"=>{["LogStash::Filters::GeoIP", {"source"=>"clientip", "id"=>"48cf85ce3f5dc3026170d3268abe03cf9acbe9d4-3"}]=>[{"thread_id"=>28, "name"=>"[main]>worker4", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.23/lib/stud/interval.rb:89:in 'sleep'"}]}}`

**Comment by amitavmohanty01** [comment] 2017-10-04 11:28
The root cause of the issue is a failure to post to elastic server. In the block for `::LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError` exception in `lib/logstash/outputs/elasticsearch/common.rb` while trying to log the URL, a sanitization was being attempted. That was failing with an exception about no such method being found. So, the original exception was being consumed. I have raised a PR (https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/692) for fixing the consumption of original exception.

Now, coming to the reason of original exception. To test I added the following lines:

```ruby
rescue ::LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError => e
        logger.error e.inspect
        logger.error "URL: #{e.url.inspect}"
```

The output I got is the following:
`[2017-10-04T15:33:49,832][ERROR][logstash.outputs.elasticsearch] #<LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError: LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError>
[2017-10-04T15:33:49,832][ERROR][logstash.outputs.elasticsearch] URL: "http://localhost:9200/_bulk"
[2017-10-04T15:33:49,832][ERROR][logstash.outputs.elasticsearch] Encountered an unexpected error submitting a bulk request! Will retry. {:error_message=>"undefined method 'sanitized' for \"http://localhost:9200/_bulk\":String", :class=>"NoMethodError", :backtrace=>["/usr/local/Cellar/logstash/5.6.2/libexec/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.4.0-java/lib/logstash/outputs/elasticsearch/common.rb:251:in 'safe_bulk'", "/usr/local/Cellar/logstash/5.6.2/libexec/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.4.0-java/lib/logstash/outputs/elasticsearch/common.rb:119:in 'submit'", "/usr/local/Cellar/logstash/5.6.2/libexec/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.4.0-java/lib/logstash/outputs/elasticsearch/common.rb:87:in 'retrying_submit'", "/usr/local/Cellar/logstash/5.6.2/libexec/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.4.0-java/lib/logstash/outputs/elasticsearch/common.rb:38:in 'multi_receive'", "/usr/local/Cellar/logstash/5.6.2/libexec/logstash-core/lib/logstash/output_delegator_strategies/shared.rb:13:in 'multi_receive'", "/usr/local/Cellar/logstash/5.6.2/libexec/logstash-core/lib/logstash/output_delegator.rb:49:in 'multi_receive'", "/usr/local/Cellar/logstash/5.6.2/libexec/logstash-core/lib/logstash/pipeline.rb:436:in `output_batch'", "org/jruby/RubyHash.java:1342:in 'each'", "/usr/local/Cellar/logstash/5.6.2/libexec/logstash-core/lib/logstash/pipeline.rb:435:in 'output_batch'", "/usr/local/Cellar/logstash/5.6.2/libexec/logstash-core/lib/logstash/pipeline.rb:381:in 
'worker_loop'", "/usr/local/Cellar/logstash/5.6.2/libexec/logstash-core/lib/logstash/pipeline.rb:342:in 'start_workers'"]}`

The first two lines show the original error and the URL that was being hit.

Looking at the original error, it seems that the pipeline configuration might not be having correct credentials to connect to ES server or some other connection issue.

In my case, I was trying to connect with "logstash_system" user. Switching to "elastic" user fixed the issue for me.

**Comment by jsvd** [comment] 2017-10-11 16:45
This issue was created due to the following message showing up in the logs: 

```
 Request will be dropped {:code=>400, :response_body=>"No handler found for uri [/_template/logstash/_bulk/_bulk/_bulk/_bulk/
```

This error came from an error in _bulk path handling which I believe was fixed in https://github.com/logstash-plugins/logstash-output-elasticsearch/commit/e1b120de658af14829043b0e57afef6812c078ae

For those seeing the `undefined method 'sanitized' `, please check follow https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/662

I'm closing this issue, please reopen if you see the multiple `/_bulk` endpoint errors with elasticsearch output >= 7.4.2 (the latest 7.x release).

**Closed by jsvd** 2017-10-11 16:45 UTC

**Comment by stefvsjay** [comment] 2018-06-05 01:59
I got this problem with logstash-output-elasticsearch 9.1.3, while 9.1.1 is OK.

**Comment by mathanv** [comment] 2018-11-21 08:06
@jsvd I am finding this issue in our setup with the following configuration. Moreover, it does not seem to be a logging issue alone - The actual ES HTTP requests are made with multiple /_bulk appended to the URL. On debugging, we have observed that /_bulk is applied to every previous request URI than the original URI, and hence the number of /_bulk appended to the final URL increases on every attempt. 

The actual requests with multiple /_bulk attached to the URL are verified using debug logs on manticore_adapter.rb as well as TCPDUMP logs. 

Please let us know if this is a configuration issue or a bug.

ES Version : 6.3
Logstash: 2.4 ( We need an older version of logstash for compatibility with older kafka brokers)
logstash-output-elasticsearch: 9.2.4 & 9.1.1 ( the issue has been observed on both)


output {
elasticsearch {
hosts => ["https://<ESDOMAIN>"]
index => "%{[@metadata][advid]}"
document_id => "%{[@metadata][key]}"
document_type => "_doc"
manage_template => false
codec => "json"
}

Actual endpoint value has been masked in the logs due to security reasons. 

{:timestamp=>"2018-11-20T21:43:21.732000+0000", :message=>"Encountered a retryable error. Will Retry with exponential backoff ", :code=>400, :url=>"https://<ESDOMAIN>/_bulk/_bulk/_bulk/_bulk", :body=>"{\"error\":\"no handler found for uri [/_bulk/_bulk/_bulk/_bulk] and method [POST]\"}", :level=>:error, :file=>"logstash/outputs/elasticsearch/common.rb", :line=>"285", :method=>"safe_bulk"}
{:timestamp=>"2018-11-20T21:43:23.800000+0000", :message=>"Encountered a retryable error. Will Retry with exponential backoff ", :code=>400, :url=>"https://<ESDOMAIN>/_bulk/_bulk/_bulk/_bulk/_bulk", :body=>"{\"error\":\"no handler found for uri [/_bulk/_bulk/_bulk/_bulk/_bulk] and method [POST]\"}", :level=>:error, :file=>"logstash/outputs/elasticsearch/common.rb", :line=>"285", :method=>"safe_bulk"}
{:timestamp=>"2018-11-20T21:43:27.886000+0000", :message=>"Encountered a retryable error. Will Retry with exponential backoff ", :code=>400, :url=>"https://<ESDOMAIN>/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk", :body=>"{\"error\":\"no handler found for uri [/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk] and method [POST]\"}", :level=>:error, :file=>"logstash/outputs/elasticsearch/common.rb", :line=>"285", :method=>"safe_bulk"}
{:timestamp=>"2018-11-20T21:43:35.959000+0000", :message=>"Encountered a retryable error. Will Retry with exponential backoff ", :code=>400, :url=>"https://<ESDOMAIN>/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk", :body=>"{\"error\":\"no handler found for uri [/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk] and method [POST]\"}", :level=>:error, :file=>"logstash/outputs/elasticsearch/common.rb", :line=>"285", :method=>"safe_bulk"}
{:timestamp=>"2018-11-20T21:43:52.055000+0000", :message=>"Encountered a retryable error. Will Retry with exponential backoff ", :code=>400, :url=>"https://<ESDOMAIN>/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk", :body=>"{\"error\":\"no handler found for uri [/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk] and method [POST]\"}", :level=>:error, :file=>"logstash/outputs/elasticsearch/common.rb", :line=>"285", :method=>"safe_bulk"}
{:timestamp=>"2018-11-20T21:44:24.121000+0000", :message=>"Encountered a retryable error. Will Retry with exponential backoff ", :code=>400, :url=>"https://<ESDOMAIN>_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk", :body=>"{\"error\":\"no handler found for uri [/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk] and method [POST]\"}", :level=>:error, :file=>"logstash/outputs/elasticsearch/common.rb", :line=>"285", :method=>"safe_bulk"}

Additional DEBUG logs added to manticore - 
{:timestamp=>"2018-11-20T21:43:09.359000+0000", :message=>"REQUEST URL: ", :url=>https://<ESDOMAIN>/, :path=>"/", :level=>:debug, :file=>"logstash/outputs/elasticsearch/http_client/manticore_adapter.rb", :line=>"67", :method=>"perform_request"}
{:timestamp=>"2018-11-20T21:43:09.691000+0000", :message=>"REQUEST URL: ", :url=>https://<ESDOMAIN>/, :path=>"/", :level=>:debug, :file=>"logstash/outputs/elasticsearch/http_client/manticore_adapter.rb", :line=>"67", :method=>"perform_request"}
{:timestamp=>"2018-11-20T21:43:13.205000+0000", :message=>"REQUEST URL: ", :url=>https://<ESDOMAIN>/, :path=>"/_bulk", :level=>:debug, :file=>"logstash/outputs/elasticsearch/http_client/manticore_adapter.rb", :line=>"67", :method=>"perform_request"}
{:timestamp=>"2018-11-20T21:43:16.454000+0000", :message=>"REQUEST URL: ", :url=>https://<ESDOMAIN>/_bulk, :path=>"/_bulk", :level=>:debug, :file=>"logstash/outputs/elasticsearch/http_client/manticore_adapter.rb", :line=>"67", :method=>"perform_request"}
{:timestamp=>"2018-11-20T21:43:19.190000+0000", :message=>"REQUEST URL: ", :url=>https://<ESDOMAIN>/_bulk/_bulk, :path=>"/_bulk", :level=>:debug, :file=>"logstash/outputs/elasticsearch/http_client/manticore_adapter.rb", :line=>"67", :method=>"perform_request"}
{:timestamp=>"2018-11-20T21:43:21.675000+0000", :message=>"REQUEST URL: ", :url=>https://<ESDOMAIN>/_bulk/_bulk/_bulk, :path=>"/_bulk", :level=>:debug, :file=>"logstash/outputs/elasticsearch/http_client/manticore_adapter.rb", :line=>"67", :method=>"perform_request"}
{:timestamp=>"2018-11-20T21:43:23.751000+0000", :message=>"REQUEST URL: ", :url=>https://<ESDOMAIN>/_bulk/_bulk/_bulk/_bulk, :path=>"/_bulk", :level=>:debug, :file=>"logstash/outputs/elasticsearch/http_client/manticore_adapter.rb", :line=>"67", :method=>"perform_request"}
{:timestamp=>"2018-11-20T21:43:27.833000+0000", :message=>"REQUEST URL: ", :url=>https://<ESDOMAIN>/_bulk/_bulk/_bulk/_bulk/_bulk, :path=>"/_bulk", :level=>:debug, :file=>"logstash/outputs/elasticsearch/http_client/manticore_adapter.rb", :line=>"67", :method=>"perform_request"}
{:timestamp=>"2018-11-20T21:43:35.907000+0000", :message=>"REQUEST URL: ", :url=>https://<ESDOMAIN>/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk, :path=>"/_bulk", :level=>:debug, :file=>"logstash/outputs/elasticsearch/http_client/manticore_adapter.rb", :line=>"67", :method=>"perform_request"}
{:timestamp=>"2018-11-20T21:43:51.984000+0000", :message=>"REQUEST URL: ", :url=>https://<ESDOMAIN>/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk, :path=>"/_bulk", :level=>:debug, :file=>"logstash/outputs/elasticsearch/http_client/manticore_adapter.rb", :line=>"67", :method=>"perform_request"}
{:timestamp=>"2018-11-20T21:44:24.078000+0000", :message=>"REQUEST URL: ", :url=>https://<ESDOMAIN>/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk/_bulk, :path=>"/_bulk", :level=>:debug, :file=>"logstash/outputs/elasticsearch/http_client/manticore_adapter.rb", :line=>"67", :method=>"perform_request"}

**Comment by sunchanglong1991** [comment] 2019-03-05 06:39
I ran into the same problem on version 6.5.1，Is there a good idea or solution?

**Comment by immunochomik** [comment] 2019-06-20 13:58
I am having the same problem on logstash 7.0.0 

```
[2019-06-20T13:35:56,668][ERROR][logstash.outputs.elasticsearch] Encountered a retryable error. Will Retry with exponential backoff  {:code=>400, :url=>"https://21a82b18e7804518a32d49eddf83a77e.eu-central-1.aws.cloud.es.io:9243/_bulk"}
[2019-06-20T13:35:58,691][ERROR][logstash.outputs.elasticsearch] Encountered a retryable error. Will Retry with exponential backoff  {:code=>400, :url=>"https://21a82b18e7804518a32d49eddf83a77e.eu-central-1.aws.cloud.es.io:9243/_bulk"}
[2019-06-20T13:36:02,709][ERROR][logstash.outputs.elasticsearch] Encountered a retryable error. Will Retry with exponential backoff  {:code=>400, :url=>"https://21a82b18e7804518a32d49eddf83a77e.eu-central-1.aws.cloud.es.io:9243/_bulk"}
```

**Comment by immunochomik** [comment] 2019-06-20 14:00
I am having the same problem in logstash 7.0.0 

"""
[2019-06-20T13:35:56,668][ERROR][logstash.outputs.elasticsearch] Encountered a retryable error. Will Retry with exponential backoff  {:code=>400, :url=>"https://21a82b18e7804518a32d49eddf83a77e.eu-central-1.aws.cloud.es.io:9243/_bulk"}
[2019-06-20T13:35:58,691][ERROR][logstash.outputs.elasticsearch] Encountered a retryable error. Will Retry with exponential backoff  {:code=>400, :url=>"https://21a82b18e7804518a32d49eddf83a77e.eu-central-1.aws.cloud.es.io:9243/_bulk"}
[2019-06-20T13:36:02,709][ERROR][logstash.outputs.elasticsearch] Encountered a retryable error. Will Retry with exponential backoff  {:code=>400, :url=>"https://********.eu-central-1.aws.cloud.es.io:9243/_bulk"}
"""

**Comment by immunochomik** [comment] 2019-06-20 14:05
I am seeing the same error on logstash 7.0.0 
```
[2019-06-20T13:35:58,691][ERROR][logstash.outputs.elasticsearch] Encountered a retryable error. Will Retry with exponential backoff  {:code=>400, :url=>"https://****.eu-central-1.aws.cloud.es.io:9243/_bulk"}
```

**Comment by GuillaumeDuf** [comment] 2019-08-01 09:15
I got the same error

**Comment by jcr0ss** [comment] 2019-09-23 11:49
i have the same issue as @mathanv, also using Logstash 2,4 because newer versions don't work with our old kafka versions . Does anyone know a fix for this?
