### ISSUE TITLE
Updating elasticsearch output breaks earlier releases of Logstash.

### ISSUE THREAD

**Issue by robcowart** [logstash-plugins/logstash-output-elasticsearch#897] opened 2019-11-15 14:38 UTC
- Version: 10.2.1
- Steps to Reproduce:
Start with something like Logstash 6.1.4 (the fastest most stable release of Logstash until this issue) and update the elasticsearch output using `logstash-plugin update logstash-output-elasticsearch`.

The errors are:

```
[2019-11-15T13:59:24,125][ERROR][logstash.pipeline        ]
Error registering plugin {
  :pipeline_id=>"blackridge",
  :plugin=>"#<LogStash::OutputDelegator:0x2586100b @namespaced_metric=#<LogStash::Instrument::NamespacedMetric:0x1388b1f6 @metric=#<LogStash::Instrument::Metric:0x437f24eb @collector=#<LogStash::Instrument::Collector:0x6dce4fd9 @agent=nil,
  @metric_store=#<LogStash::Instrument::MetricStore:0x78dd0c23 @store=#<Concurrent::Map:0x2e8c05cf entries=3 default_proc=nil>,
  @structured_lookup_mutex=#<Mutex:0x14ee2489>,
  @fast_lookup=#<Concurrent::Map:0xb41114a entries=284 default_proc=nil>>>>,
  @namespace_name=[
    :stats,
    :pipelines,
    :blackridge,
    :plugins,
    :outputs,
    :bd5484d7f694d38abe2717caad7e29b42a992bcf807c4f63784edd48cf039afe
  ]>,
  @metric=#<LogStash::Instrument::NamespacedMetric:0x558174ca @metric=#<LogStash::Instrument::Metric:0x437f24eb @collector=#<LogStash::Instrument::Collector:0x6dce4fd9 @agent=nil,
  @metric_store=#<LogStash::Instrument::MetricStore:0x78dd0c23 @store=#<Concurrent::Map:0x2e8c05cf entries=3 default_proc=nil>,
  @structured_lookup_mutex=#<Mutex:0x14ee2489>,
  @fast_lookup=#<Concurrent::Map:0xb41114a entries=284 default_proc=nil>>>>,
  @namespace_name=[
    :stats
    :pipelines,
    :blackridge,
    :plugins,
    :outputs
  ]>,
  @logger=#<LogStash::Logging::Logger:0x33e65491 @logger=#<Java::OrgApacheLoggingLog4jCore::Logger:0x45bdffe8>>,
  @out_counter=org.jruby.proxy.org.logstash.instrument.metrics.counter.LongCounter$Proxy2 -  name: out value:0,
  @strategy=#<LogStash::OutputDelegatorStrategies::Shared:0x5de8bd76 @output=<LogStash::Outputs::ElasticSearch hosts=>[//127.0.0.1:9200], user=>\"elastic\", password=><password>, index=>\"blackridge-3.0.0-%{+YYYY.MM.dd}\", template=>\"/etc/logstash/blackridge/templates/blackridge.template.json\", template_name=>\"blackridge-3.0.0\", template_overwrite=>true, id=>\"bd5484d7f694d38abe2717caad7e29b42a992bcf807c4f63784edd48cf039afe\", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>\"plain_c4f0ad5c-2d45-40b2-8371-d340c15e7e3c\", enable_metric=>true, charset=>\"UTF-8\">, workers=>1, manage_template=>true, doc_as_upsert=>false, script_type=>\"inline\", script_lang=>\"painless\", script_var_name=>\"event\", scripted_upsert=>false, retry_initial_interval=>2, retry_max_interval=>64, retry_on_conflict=>1, ilm_enabled=>\"auto\", ilm_rollover_alias=>\"logstash\", ilm_pattern=>\"{now/d}-000001\", ilm_policy=>\"logstash-policy\", action=>\"index\",
  ssl_certificate_verification=>true,
  sniffing=>false,
  sniffing_delay=>5,
  timeout=>60,
  pool_max=>1000,
  pool_max_per_route=>100,
  resurrect_delay=>5,
  validate_after_inactivity=>10000,
  http_compression=>false,
  metric=>#<LogStash::Instrument::NamespacedMetric:0x1388b1f6 @metric=#<LogStash::Instrument::Metric:0x437f24eb @collector=#<LogStash::Instrument::Collector:0x6dce4fd9 @agent=nil,
  @metric_store=#<LogStash::Instrument::MetricStore:0x78dd0c23 @store=#<Concurrent::Map:0x2e8c05cf entries=3 default_proc=nil>,
  @structured_lookup_mutex=#<Mutex:0x14ee2489>,
  @fast_lookup=#<Concurrent::Map:0xb41114a entries=284 default_proc=nil>>>>,
  @namespace_name=[
    :stats,
    :pipelines,
    :blackridge,
    :plugins,
    :outputs,
    :bd5484d7f694d38abe2717caad7e29b42a992bcf807c4f63784edd48cf039afe
  ]>>>,
  @in_counter=org.jruby.proxy.org.logstash.instrument.metrics.counter.LongCounter$Proxy2 -  name: in value:0,
  @id=\"bd5484d7f694d38abe2717caad7e29b42a992bcf807c4f63784edd48cf039afe\",
  @time_metric=org.jruby.proxy.org.logstash.instrument.metrics.counter.LongCounter$Proxy2 -  name: duration_in_millis value:0,
  @metric_events=#<LogStash::Instrument::NamespacedMetric:0x5c2b2886 @metric=#<LogStash::Instrument::Metric:0x437f24eb @collector=#<LogStash::Instrument::Collector:0x6dce4fd9 @agent=nil,
  @metric_store=#<LogStash::Instrument::MetricStore:0x78dd0c23 @store=#<Concurrent::Map:0x2e8c05cf entries=3 default_proc=nil>,
  @structured_lookup_mutex=#<Mutex:0x14ee2489>,
  @fast_lookup=#<Concurrent::Map:0xb41114a entries=284 default_proc=nil>>>>,
  @namespace_name=[
    :stats,
    :pipelines,
    :blackridge,
    :plugins,
    :outputs,
    :bd5484d7f694d38abe2717caad7e29b42a992bcf807c4f63784edd48cf039afe,
    :events
  ]>,
  @output_class=LogStash::Outputs::ElasticSearch>",
  :error=>"uninitialized constant LogStash::OSS",
  :thread=>"#<Thread:0x340e51cf@/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:245 run>"
}

[2019-11-15T13:59:24,130][ERROR][logstash.pipeline        ]
Pipeline aborted due to error {
  :pipeline_id=>"blackridge",
  :exception=>#<NameError: uninitialized constant LogStash::OSS>,
  :backtrace=>["org/jruby/RubyModule.java:3343:in `const_missing'",
  "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-10.2.1-java/lib/logstash/outputs/elasticsearch.rb:248:in `oss?'",
  "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-10.2.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:72:in `oss?'",
  "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-10.2.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:285:in `block in healthcheck!'",
  "org/jruby/ext/thread/Mutex.java:148:in `synchronize'",
  "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-10.2.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:275:in `block in healthcheck!'",
  "org/jruby/RubyHash.java:1343:in `each'",
  "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-10.2.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:266:in `healthcheck!'",
  "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-10.2.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:382:in `update_urls'",
  "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-10.2.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:82:in `update_initial_urls'",
  "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-10.2.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:76:in `start'",
  "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-10.2.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:302:in `build_pool'",
  "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-10.2.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:64:in `initialize'",
  "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-10.2.1-java/lib/logstash/outputs/elasticsearch/http_client_builder.rb:103:in `create_http_client'",
  "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-10.2.1-java/lib/logstash/outputs/elasticsearch/http_client_builder.rb:99:in `build'",
  "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-10.2.1-java/lib/logstash/outputs/elasticsearch.rb:238:in `build_client'",
  "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-10.2.1-java/lib/logstash/outputs/elasticsearch/common.rb:25:in `register'",
  "/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/shared.rb:9:in `register'",
  "/usr/share/logstash/logstash-core/lib/logstash/output_delegator.rb:43:in `register'",
  "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:343:in `register_plugin'",
  "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:354:in `block in register_plugins'",
  "org/jruby/RubyArray.java:1734:in `each'",
  "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:354:in `register_plugins'",
  "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:743:in `maybe_setup_out_plugins'",
  "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:364:in `start_workers'",
  "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:288:in `run'",
  "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:248:in `block in start'"],
  :thread=>"#<Thread:0x340e51cf@/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:245 run>"
}
```

The important information being `:exception=>#<NameError: uninitialized constant LogStash::OSS>,`, which was introduced in https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/875/files

**Comment by kares** [comment] 2022-02-03 07:01
given this is regarding 6.1.4 at Nov 2019 I believe the intent was that the plugin continues to support up-to-date LS 6.x (6.8 at that time). it's would be tricky to have a fine level of version requirements in every plugin, usually a patch version plugin update is guaranteed to work, minor might but a new major is pretty much unknown territory.

the cause for this issue (`Logstash::OSS` constant) could be considered resolved with [the removal](https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1005/files#diff-67f3b8d872aba6e0a173ae7b1bf9de4d7dcf1540a64343162aeb8802a30949a7L34) of 2 separate code paths (oss and non-oss) in the plugin but I do not suggest to update while staying on LS 6.1

**Closed by kares** 2022-02-03 07:01 UTC
